import { test, expect } from '@playwright/test'

function dateDaysAgo(days) {
  const date = new Date()
  date.setHours(12, 0, 0, 0)
  date.setDate(date.getDate() - days)
  return date.toISOString().slice(0, 10)
}

async function createBaby(page) {
  await page.goto('/#/login')
  await page.getByLabel('账号').fill('test-admin')
  await page.getByLabel('密码').fill('test-password')
  await page.getByRole('button', { name: '登录' }).click()
  await expect(page).toHaveURL(/#\/(onboarding|today)$/)
  if (page.url().endsWith('#/today')) return
  await page.goto('/#/onboarding')
  await page.getByLabel('家庭名称').fill('小舟的家庭')
  await page.getByLabel('宝宝昵称').fill('小舟')
  await page.getByLabel('出生日期').fill(dateDaysAgo(6))
  await page.getByLabel('出生孕周').fill('39')
  await page.getByLabel('男孩').check()
  await page.getByLabel('喂养方式').selectOption('mixed')
  await page.getByRole('button', { name: '进入 BabyForge' }).click()
  await expect(page).toHaveURL(/#\/today$/)
}

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
})

test('today tasks hand off to the growth read model and growth facts loop back to records', async ({ page }) => {
  await createBaby(page)
  const newParentGuide = page.locator('.new-parent-guide')
  const daily = page.getByTestId('daily-health-reminders')
  await expect(newParentGuide.getByText('新手父母关注', { exact: true })).toBeVisible()
  await expect(newParentGuide.getByText('崔玉涛公开科普提炼 · 第1个月', { exact: true })).toBeVisible()
  await expect(newParentGuide.getByText('护理重点', { exact: true })).toBeVisible()
  await expect(newParentGuide.getByText('早教安排', { exact: true })).toBeVisible()
  await expect(newParentGuide).toContainText('脐带脱落')
  await expect(page.getByTestId('growth-roadmap')).toHaveCount(0)
  await expect(page.locator('.today-middle-column > .baby-album-surface')).toBeVisible()
  await expect(page.locator('.stage-timeline-list')).toHaveCount(0)
  await expect(page.getByTestId('today-care-summary')).toBeVisible()
  await expect(page.getByTestId('context-inspector')).toBeVisible()
  await expect(page.getByTestId('context-inspector').getByTestId('daily-health-reminders')).toBeVisible()
  await expect(page.getByTestId('context-inspector').locator('.stage-inspector')).toHaveCount(0)
  await expect(daily).toBeVisible()
  await expect(daily.getByText('作息表建议', { exact: true })).toBeVisible()
  await expect(daily.getByText('营养补充', { exact: true })).toBeVisible()
  await expect(daily.getByText('护理重点', { exact: true })).toHaveCount(0)
  await expect(daily.getByText('早教安排', { exact: true })).toHaveCount(0)
  await expect(page.locator('.left-rail > *').nth(1)).toHaveAttribute('data-testid', 'today-care-summary')
  await expect(page.locator('.left-rail > *').nth(2)).toHaveClass(/new-parent-guide/)
  await expect(page.getByText('当前角色', { exact: true })).toHaveCount(1)
  await expect(page.getByText('稍后', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '成长', exact: true }).click()
  await expect(page.getByTestId('growth-roadmap')).toBeVisible()
  await expect(page.locator('.growth-roadmap-item.active')).toContainText('新生儿早期')
  await expect(page.getByText('成长数据', { exact: true })).toBeVisible()
  await expect(page.getByTestId('growth-admin-task-list')).toHaveCount(0)
  await expect(page.getByText('办理出生医学证明', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('近期测量变化', { exact: true })).toBeVisible()
  await expect(page.getByText('父母建议完成', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '去记录中心录入成长测量' }).click()
  await page.getByLabel('数值').fill('3.4')
  await page.getByRole('button', { name: '保存事实' }).click()
  await page.getByRole('button', { name: '成长', exact: true }).click()
  await expect(page.locator('.growth-metric-card').first()).toContainText('3.4 kg')
  await page.getByRole('button', { name: '健康', exact: true }).click()
  await page.getByRole('tab', { name: '常见儿科病', exact: true }).click()
  const diseaseFinder = page.getByPlaceholder('搜索疾病正式名、别名或俗称…')
  await diseaseFinder.fill('普通感冒')
  await page.locator('.disease-topic-card').filter({ has: page.getByRole('heading', { name: '普通感冒', exact: true }) }).click()
  const selectedDisease = page.locator('.disease-selected')
  await expect(selectedDisease.getByRole('heading', { name: '普通感冒', exact: true })).toBeVisible()
  await expect(selectedDisease.getByRole('heading', { name: '病因', exact: true })).toBeVisible()
  await expect(selectedDisease.getByRole('heading', { name: '身体里发生了什么', exact: true })).toBeVisible()
  await expect(page.getByText('打开黄疸认知专题')).toHaveCount(0)
})

test('growth roadmap opens stage education in place without leaving today', async ({ page }) => {
  await createBaby(page)
  await page.getByRole('button', { name: '成长', exact: true }).click()
  const nextStage = page.locator('.growth-roadmap-item[data-stage-id="newborn-adaptation"]')
  await nextStage.click()

  await expect(page).toHaveURL(/#\/growth$/)
  const dialog = page.locator('.growth-roadmap-dialog')
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText('出生后 8–28 天')
  await expect(dialog).toContainText('本阶段宝宝通常是什么样')
  await expect(dialog).toContainText('本阶段关键点')
  await expect(dialog).toContainText('阶段结束时可能看到')
  await expect(dialog).toContainText('清醒片段')
  await expect(dialog).toContainText('科普依据')
  await dialog.getByRole('button', { name: '关闭阶段介绍' }).click()
  await expect(dialog).toBeHidden()
})

test('growth entry preserves metric context and opens the original CareEvent', async ({ page }) => {
  await createBaby(page)
  await page.getByRole('button', { name: '成长', exact: true }).click()
  await page.getByRole('button', { name: '去记录中心录入成长测量' }).click()
  await expect(page).toHaveURL(/#\/records\?panel=growth&returnTo=%23%2Fgrowth$/)
  await page.getByTestId('record-entry-growth').getByLabel('类型').selectOption('headCircumference')
  await page.getByTestId('record-entry-growth').getByLabel('数值').fill('35')
  await page.getByRole('button', { name: '保存事实' }).click()
  await expect(page).toHaveURL(/#\/growth$/)
  await expect(page.locator('.growth-metric-card').filter({ hasText: '头围' })).toContainText('35 cm')

  await page.locator('.growth-metric-card').filter({ hasText: '头围' }).getByRole('button', { name: '去记录' }).click()
  await expect(page).toHaveURL(/#\/records\?panel=growth&metric=headCircumference&returnTo=%23%2Fgrowth$/)
  await expect(page.getByTestId('record-entry-growth').getByLabel('类型')).toHaveValue('headCircumference')
  await page.getByTestId('record-entry-growth').getByRole('button', { name: '取消' }).click()
  await expect(page).toHaveURL(/#\/growth$/)

  await page.getByRole('button', { name: '查看原记录' }).first().click()
  await expect(page).toHaveURL(/#\/records\?panel=growth&event=.*&mode=detail&returnTo=%23%2Fgrowth$/)
  await expect(page.getByTestId('record-event-detail')).toContainText('头围 35 cm')
  await page.getByTestId('record-event-detail').getByRole('button', { name: '关闭' }).click()
  await expect(page).toHaveURL(/#\/growth$/)
})

test('today is view-only and records stay in the record center', async ({ page }) => {
  await createBaby(page)
  const summary = page.getByTestId('today-care-summary')
  await expect(summary).toBeVisible()
  await expect(summary.getByRole('heading', { name: '照护汇总' })).toBeVisible()
  await expect(page.getByText(/仅查看/)).toHaveCount(0)
  await expect(summary.getByRole('button', { name: '喂养 · 查看今天记录' })).toBeVisible()
  await expect(summary.getByRole('button', { name: '睡眠 · 查看今天记录' })).toBeVisible()
  await expect(summary.getByRole('button', { name: '尿布 · 查看今天记录' })).toBeVisible()
  await expect(summary.getByRole('button', { name: '用药 · 查看今天记录' })).toBeVisible()
  await expect(page.getByLabel('发生时间')).toHaveCount(0)
  await summary.getByRole('button', { name: '喂养 · 查看今天记录' }).click()
  await expect(page).toHaveURL(/#\/records\?filter=feeding&date=today&returnTo=%23%2Ftoday$/)
  await expect(page.getByTestId('care-timeline')).toBeVisible()
  await page.locator('.record-card').filter({ hasText: '喂奶' }).click()
  await page.getByTestId('record-entry-feeding').getByRole('button', { name: '配方奶' }).click()
  await page.getByLabel('实际喝下奶量').fill('60')
  await page.getByRole('button', { name: '保存事实' }).click()
  await expect(page).toHaveURL(/#\/today$/)
  await page.getByRole('button', { name: '新增喂养' }).click()
  await expect(page).toHaveURL(/#\/records\?panel=feeding&returnTo=%23%2Ftoday$/)
  await page.getByTestId('record-entry-feeding').getByRole('button', { name: '取消' }).click()
  await expect(page).toHaveURL(/#\/today$/)
  await page.getByTestId('today-care-summary').getByRole('button', { name: '喂养 · 查看今天记录' }).click()
  await expect(page).toHaveURL(/#\/records\?filter=feeding&date=today&returnTo=%23%2Ftoday$/)
  await expect(page.getByText('配方奶 60 mL', { exact: true }).first()).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: '作废 配方奶 60 mL' }).click()
  await expect(page.getByText('配方奶 60 mL', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '就医摘要', exact: true }).click()
  await expect(page).toHaveURL(/#\/doctor-summary$/)
})
