import { test, expect } from '@playwright/test'

function dateDaysAgo(days) {
  const date = new Date()
  date.setHours(12, 0, 0, 0)
  date.setDate(date.getDate() - days)
  return date.toISOString().slice(0, 10)
}

async function createBaby(page) {
  await page.goto('/#/login')
  await page.getByLabel('账号').fill('niwa')
  await page.getByLabel('密码').fill('niwaniwa')
  await page.getByRole('button', { name: '登录' }).click()
  await expect(page).toHaveURL(/#\/(onboarding|today)$/)
  if (page.url().endsWith('#/today')) return
  await page.goto('/#/onboarding')
  await page.getByLabel('宝宝昵称').fill('小舟')
  await page.getByLabel('出生日期').fill(dateDaysAgo(6))
  await page.getByLabel('出生孕周').fill('39')
  await page.getByLabel('男孩').check()
  await page.getByLabel('喂养方式').selectOption('mixed')
  await page.getByRole('button', { name: '进入 BabyForge' }).click()
}

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
})

test('today tasks hand off to the growth read model and growth facts loop back to records', async ({ page }) => {
  await createBaby(page)
  await expect(page.getByText('新手父母关注', { exact: true })).toBeVisible()
  await expect(page.getByText('喂养后看一眼', { exact: true })).toBeVisible()
  await expect(page.getByText('这些变化要及时求助', { exact: true })).toBeVisible()
  await expect(page.locator('.stage-timeline-list .timeline-item')).toHaveCount(15)
  await expect(page.getByTestId('care-task-list').first()).toBeVisible()
  await expect(page.getByTestId('admin-task-list')).toBeVisible()
  await expect(page.getByText('办理出生医学证明', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('核对出生相关疫苗记录', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: /办理出生医学证明.*标记完成/ }).first().click()
  await expect(page.getByRole('button', { name: /办理出生医学证明.*已完成/ }).first()).toBeVisible()
  await expect(page.getByText('当前角色', { exact: true })).toHaveCount(1)
  await expect(page.getByText('稍后', { exact: true })).toHaveCount(0)
  await expect(page.getByTestId('care-task-list').last().getByText('完成标准：', { exact: true })).toHaveCount(3)
  await page.getByRole('button', { name: /观察一次完整喂养.*标记完成/ }).first().click()
  await expect(page.getByRole('button', { name: /观察一次完整喂养.*已完成/ }).first()).toBeVisible()
  await page.getByRole('button', { name: '成长', exact: true }).click()
  await expect(page.getByRole('heading', { name: '最近成长测量' })).toBeVisible()
  await expect(page.getByText('国家标准参考', { exact: true })).toBeVisible()
  await expect(page.getByText('父母建议完成', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '去记录中心录入成长测量' }).click()
  await page.getByLabel('数值').fill('3.4')
  await page.getByRole('button', { name: '保存事实' }).click()
  await page.getByRole('button', { name: '成长', exact: true }).click()
  await expect(page.locator('.growth-metric-card').first()).toContainText('3.4 kg')
  await page.getByRole('button', { name: '常见儿科病', exact: true }).click()
  await page.getByRole('button', { name: /呼吸道症状/ }).click()
  await page.getByRole('button', { name: /普通感冒（急性上呼吸道感染）/ }).click()
  const dialog = page.getByRole('dialog', { name: /普通感冒/ })
  await expect(dialog.getByText('可能成因')).toBeVisible()
  await expect(dialog.getByRole('heading', { name: '可能影响' })).toBeVisible()
  await expect(page.getByText('打开黄疸认知专题')).toHaveCount(0)
})

test('today quick records form a low-burden care loop', async ({ page }) => {
  await createBaby(page)
  await page.getByLabel('发生时间').fill('2026-08-03T09:30')
  await page.getByTestId('quick-record-urine').click()
  await expect(page.getByText('只有尿', { exact: true }).first()).toBeVisible()
  await page.getByTestId('quick-record-bottle_feeding').click()
  await page.getByLabel('实际喝下奶量').fill('60')
  await page.getByRole('button', { name: '保存瓶喂' }).click()
  await expect(page.getByText('瓶喂 60 mL', { exact: true }).first()).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: '撤销瓶喂 60 mL' }).click()
  await expect(page.getByText('瓶喂 60 mL', { exact: true })).toHaveCount(0)
  await expect(page).toHaveURL(/#\/today$/)
  await expect(page.getByRole('button', { name: '就医摘要' })).toHaveCount(0)
  await expect(page.getByText('当前角色', { exact: true })).toHaveCount(1)
})
