-- D1's migration endpoint appends its tracking INSERT to each migration and
-- submits the whole file as one SQL request. SQLite trigger bodies contain an
-- internal semicolon, which that endpoint currently parses as incomplete input.
-- Canonical fields are therefore enforced at the Worker write boundary in
-- functions/_shared/care.js. Keep this migration as an intentional no-op so the
-- migration ledger can advance without leaving a partially applied database.
