import { ANATOMY_RESOURCES } from './pediatricDiseases.js'

const t = (zh, en) => Object.freeze({ zh, en })
const items = (zh, en) => zh.split('|').map((value, index) => t(value, en.split('|')[index] || value))

export const DISEASE_CONTENT_VERSION = 'disease-registry-2026-08-08'

export const DISEASE_SOURCES = Object.freeze({
  aapCommon: { id: 'aap-common-childhood-illnesses', label: t('美国儿科学会：常见儿童疾病', 'American Academy of Pediatrics: common childhood illnesses'), url: 'https://www.healthychildren.org/English/health-issues/conditions/treatments/Pages/10-Common-Childhood-Illnesses-and-Their-Treatments.aspx' },
  cdcRespiratory: { id: 'cdc-respiratory-viruses', label: t('美国疾控中心：呼吸道病毒', 'CDC: respiratory viruses'), url: 'https://www.cdc.gov/respiratory-viruses/' },
  cdcVaccines: { id: 'cdc-vaccine-preventable-diseases', label: t('美国疾控中心：疫苗可预防疾病', 'CDC: vaccine-preventable diseases'), url: 'https://www.cdc.gov/vaccines/by-disease/index.html' },
  cdcHfmd: { id: 'cdc-hand-foot-mouth', label: t('美国疾控中心：手足口病', 'CDC: hand, foot and mouth disease'), url: 'https://www.cdc.gov/hand-foot-mouth/' },
  nhsChildren: { id: 'nhs-child-health', label: t('英国国家医疗服务体系：儿童健康', 'NHS: children\'s health'), url: 'https://www.nhs.uk/conditions/baby/health/' },
  nhsSkin: { id: 'nhs-skin-conditions', label: t('英国国家医疗服务体系：皮肤问题', 'NHS: skin conditions'), url: 'https://www.nhs.uk/conditions/' },
  whoChild: { id: 'who-child-health', label: t('世界卫生组织：儿童健康', 'WHO: child health'), url: 'https://www.who.int/health-topics/child-health' },
  whoPneumonia: { id: 'who-child-pneumonia', label: t('世界卫生组织：儿童肺炎', 'WHO: pneumonia in children'), url: 'https://www.who.int/news-room/fact-sheets/detail/pneumonia' },
})

const CATEGORIES = Object.freeze({
  newborn: t('新生儿与小婴儿', 'Newborn & young infant'),
  respiratory: t('呼吸系统', 'Respiratory'),
  infectious: t('常见传染病', 'Common infections'),
  ent: t('耳鼻喉与口腔', 'ENT & oral'),
  digestive: t('消化系统', 'Digestive'),
  skin: t('皮肤与过敏', 'Skin & allergy'),
  eye: t('眼部', 'Eye'),
  urinary: t('泌尿与生殖', 'Urinary & genital'),
  neurologic: t('神经系统急性问题', 'Acute neurologic'),
  nutrition: t('营养、血液与生长', 'Nutrition, blood & growth'),
})

const PROFILES = Object.freeze({
  newborn: {
    observation: items('记录出现时间和出生后日龄|观察吃奶、精神、体温和尿便|记录变化趋势及已有检查', 'Record onset and age in days|Observe feeding, alertness, temperature and output|Keep the trend and existing test results'),
    management: t('医疗机构通常先评估生命体征、喂养与脱水情况，再按病因决定检查和支持治疗。', 'Clinicians usually assess vital signs, feeding and hydration before choosing cause-specific tests and supportive care.'),
    homeCare: items('按原有安全喂养计划继续观察|保持日常记录并按预约复查', 'Continue the established safe feeding plan while observing|Keep daily records and attend planned follow-up'),
    avoid: items('不自行使用处方药或偏方|不因短暂好转忽略新生儿状态变化', 'Do not use prescription medicines or remedies without clinical advice|Do not dismiss a newborn state change after brief improvement'),
    prevention: items('规范手卫生与脐部、口腔或皮肤护理|按儿童保健安排完成筛查与随访', 'Use careful hand and cord, mouth or skin hygiene|Complete screening and follow-up through child health care'),
  },
  respiratory: {
    observation: items('观察呼吸是否比平时费力或增快|记录咳嗽、喘鸣、发热与睡眠变化|记录饮水、进食和尿量趋势', 'Watch for breathing that is harder or faster than usual|Record cough, wheeze, fever and sleep changes|Track fluids, food and urine'),
    management: t('医疗机构会评估呼吸和氧合，根据病因与严重程度决定是否需要检测、支持治疗或处方治疗。', 'Clinicians assess breathing and oxygenation, then choose tests, supportive care or prescription treatment according to cause and severity.'),
    homeCare: items('保证休息并少量多次补充液体|保持环境无烟并观察呼吸与精神状态', 'Allow rest and offer fluids in small frequent amounts|Keep the environment smoke-free and watch breathing and alertness'),
    avoid: items('不自行使用抗生素或处方止咳药|不把喘鸣或呼吸费力只当作普通咳嗽', 'Do not start antibiotics or prescription cough medicine without advice|Do not treat wheeze or labored breathing as an ordinary cough'),
    prevention: items('手卫生、通风并减少患病期间密切接触|按当地计划接种适龄疫苗', 'Use hand hygiene, ventilation and less close contact while ill|Follow the local age-appropriate vaccine schedule'),
  },
  infectious: {
    observation: items('记录发热、皮疹或局部表现的开始顺序|观察饮水、进食、尿量与精神状态|记录接触史、托幼出勤和疫苗史', 'Record the order in which fever, rash or local signs appeared|Watch fluids, food, urine and alertness|Record contacts, childcare attendance and vaccine history'),
    management: t('医疗机构根据接触史、查体和必要检测判断病因，重点处理补液、舒适度和并发问题。', 'Clinicians use exposure history, examination and selected tests to determine cause, with focus on hydration, comfort and complications.'),
    homeCare: items('保证液体摄入并保持皮肤口腔清洁|患病期间减少与他人密切接触', 'Maintain fluid intake and gentle skin and mouth care|Reduce close contact with others while ill'),
    avoid: items('不抓破皮疹或共用个人用品|不自行使用抗生素或处方药', 'Avoid scratching lesions or sharing personal items|Do not use antibiotics or prescription medicine without advice'),
    prevention: items('勤洗手并清洁高频接触表面|按当地计划完成疫苗接种', 'Wash hands and clean frequently touched surfaces|Complete vaccines according to the local schedule'),
  },
  ent: {
    observation: items('记录疼痛、分泌物、吞咽或听力变化|观察发热、睡眠和进食|记录单侧或双侧及持续时间', 'Record pain, discharge, swallowing or hearing changes|Watch fever, sleep and intake|Record side and duration'),
    management: t('需要通过耳、鼻、咽或口腔检查区分病毒、细菌、刺激和结构问题，再决定观察、支持或处方治疗。', 'Examination of the ear, nose, throat or mouth distinguishes viral, bacterial, irritant and structural causes before observation, support or prescription treatment is chosen.'),
    homeCare: items('补充液体并提供柔软易吞咽食物|保持鼻腔、外耳或口腔清洁舒适', 'Offer fluids and easy-to-swallow foods|Keep the nose, outer ear or mouth clean and comfortable'),
    avoid: items('不把棉签、油或未经建议的滴剂放入耳内|不自行使用抗生素', 'Do not put cotton buds, oil or unadvised drops in the ear|Do not start antibiotics without clinical advice'),
    prevention: items('手卫生并避免烟雾刺激|规范口腔护理和个人用品管理', 'Use hand hygiene and avoid smoke exposure|Maintain oral care and do not share personal items'),
  },
  digestive: {
    observation: items('记录呕吐、腹泻、腹痛或排便的时间与次数|观察进食、饮水、尿量和精神状态|记录腹部外观及粪便特征', 'Record timing and frequency of vomiting, diarrhea, pain or stools|Watch intake, urine and alertness|Record abdominal appearance and stool features'),
    management: t('医疗机构先评估脱水与腹部体征，再按感染、功能或结构原因选择补液、检查和治疗。', 'Clinicians first assess hydration and abdominal signs, then choose fluids, tests and treatment for infectious, functional or structural causes.'),
    homeCare: items('少量多次补液并继续适合年龄的饮食|记录尿量、排便和症状趋势', 'Offer small frequent fluids and continue age-appropriate foods|Track urine, stools and symptom trends'),
    avoid: items('不自行使用止泻药、抗生素或偏方|不强迫进食或用大量单一液体替代正常补液', 'Do not self-start antidiarrheals, antibiotics or remedies|Do not force food or replace proper rehydration with large amounts of one drink'),
    prevention: items('手卫生、食品和饮水安全|按建议进行喂养与便秘预防', 'Use hand hygiene and safe food and water|Follow feeding and constipation-prevention advice'),
  },
  skin: {
    observation: items('记录皮疹位置、范围、颜色与表面变化|观察瘙痒、疼痛、渗液及是否扩散|记录新食物、用品、药物和接触史', 'Record rash site, extent, color and surface changes|Watch itch, pain, weeping and spread|Record new foods, products, medicines and contacts'),
    management: t('医疗机构根据皮疹形态、分布和接触史区分炎症、过敏与感染，必要时进行检测并选择局部或全身治疗。', 'Clinicians use rash appearance, distribution and exposure history to distinguish inflammation, allergy and infection, adding tests and topical or systemic treatment when needed.'),
    homeCare: items('温和清洁、保持皮肤屏障并剪短指甲|停用近期新增且可疑的刺激用品', 'Clean gently, protect the skin barrier and keep nails short|Stop newly introduced suspected irritants when safe to do so'),
    avoid: items('不抓挠、挤压或自行混用药膏|不把快速扩散或伴全身不适的皮疹仅当皮肤问题', 'Do not scratch, squeeze or mix medicated creams without advice|Do not treat a rapidly spreading rash with systemic illness as only a skin problem'),
    prevention: items('减少已知刺激物并使用温和护理|保持手卫生且不共用毛巾', 'Reduce known irritants and use gentle skin care|Use hand hygiene and do not share towels'),
  },
  eye: {
    observation: items('比较单侧与双侧红肿、分泌物和睁眼情况|记录开始时间、接触史及视物反应|观察疼痛、畏光和眼周肿胀', 'Compare redness, swelling, discharge and eye opening on both sides|Record onset, contacts and visual response|Watch pain, light sensitivity and swelling around the eye'),
    management: t('医疗机构通过眼睑、结膜、角膜和泪道检查判断感染、堵塞或刺激，必要时选择清洁、随访或处方治疗。', 'Clinicians examine eyelids, conjunctiva, cornea and tear ducts to distinguish infection, blockage and irritation, then choose cleaning, follow-up or prescription treatment.'),
    homeCare: items('洗手后用清洁材料从内向外轻拭分泌物|每只眼使用独立清洁材料', 'After handwashing, gently wipe discharge outward with clean material|Use separate cleaning material for each eye'),
    avoid: items('不共用毛巾或自行使用剩余眼药|不揉眼或挤压眼睑肿块', 'Do not share towels or use leftover eye medicine|Do not rub the eye or squeeze an eyelid lump'),
    prevention: items('手卫生并减少眼部分泌物接触|保持毛巾和枕巾清洁', 'Use hand hygiene and avoid contact with eye discharge|Keep towels and pillowcases clean'),
  },
  urinary: {
    observation: items('记录排尿次数、疼痛、尿色和气味|观察体温、腹痛、腰背痛与精神状态|记录饮水、尿量及既往感染', 'Record urine frequency, pain, color and odor|Watch temperature, abdominal or back pain and alertness|Track fluids, urine volume and previous infections'),
    management: t('医疗机构通常需要规范尿样和查体确认感染或炎症，按年龄与结果决定检查和处方治疗。', 'Clinicians commonly need a proper urine sample and examination to confirm infection or inflammation, then choose tests and prescription treatment by age and findings.'),
    homeCare: items('保证适龄液体摄入并及时更换尿布|保持外阴清洁干燥，按前向后清洁', 'Maintain age-appropriate fluids and change diapers promptly|Keep the genital area clean and dry, wiping front to back'),
    avoid: items('不使用剩余抗生素或刺激性清洁品|不因症状减轻而自行停用处方治疗', 'Do not use leftover antibiotics or harsh cleansers|Do not stop prescribed treatment when symptoms ease'),
    prevention: items('规律排尿、适量饮水并避免便秘|保持温和卫生习惯', 'Use regular toileting, adequate fluids and constipation prevention|Maintain gentle hygiene'),
  },
  neurologic: {
    observation: items('记录发作开始、持续时间和恢复过程|观察意识、呼吸、肤色及动作是否对称|在安全前提下记录视频并保留体温资料', 'Record onset, duration and recovery|Watch awareness, breathing, color and symmetry|If safe, record a video and keep temperature information'),
    management: t('医疗机构会先稳定呼吸循环并判断是否为惊厥，再按年龄、发热和查体结果寻找原因。', 'Clinicians first stabilize breathing and circulation and determine whether an event was a seizure, then investigate according to age, fever and examination.'),
    homeCare: items('让孩子侧卧于安全平面并移开周围硬物|记录时间并在发作停止后继续观察反应', 'Place the child on their side on a safe surface and move hard objects away|Time the event and watch responsiveness after it stops'),
    avoid: items('不按压肢体、不往口中放物体|不在意识未恢复时喂水或食物', 'Do not restrain limbs or put anything in the mouth|Do not offer food or drink before awareness returns'),
    prevention: items('按计划管理基础疾病和发热相关不适|让所有照护者了解安全处置方法', 'Follow plans for underlying illness and fever discomfort|Make sure all caregivers know seizure first aid'),
  },
  nutrition: {
    observation: items('记录饮食结构、奶量和补充剂来源|观察面色、活动耐力、骨骼和生长变化|保留成长曲线与化验结果', 'Record diet, milk and supplement sources|Watch color, stamina, bones and growth|Keep growth charts and laboratory results'),
    management: t('医疗机构结合饮食史、生长测量和必要化验确认缺乏，再制定饮食、补充与复查计划。', 'Clinicians combine diet history, growth measurements and selected tests to confirm deficiency and plan diet, supplementation and follow-up.'),
    homeCare: items('提供年龄适宜且多样的饮食|按专业建议使用补充剂并记录', 'Offer a varied age-appropriate diet|Use supplements only as advised and keep a record'),
    avoid: items('不自行使用成人剂量补充剂|不以单一食物或保健品替代评估', 'Do not use adult-dose supplements|Do not substitute one food or supplement for assessment'),
    prevention: items('定期儿童保健并监测生长|按当地建议落实营养与户外活动', 'Attend child health visits and monitor growth|Follow local nutrition and outdoor-activity advice'),
  },
})

const DEFAULT_PREPARATION = items('症状开始时间和变化趋势|体温、饮水进食、尿便和精神记录|已经使用的药物或处理|接触史、基础疾病和既往检查', 'Symptom onset and trend|Temperature, intake, output and alertness records|Medicines or care already used|Contacts, underlying conditions and previous tests')

function defaultDisplayUnit(input) {
  const preciseSkinTopics = new Set(['atopic-dermatitis', 'diaper-dermatitis', 'contact-dermatitis', 'heat-rash', 'impetigo', 'fungal-skin-infection'])
  const skinResource = ANATOMY_RESOURCES.find((resource) => resource.id === 'skin')
  const resourceIds = new Set(ANATOMY_RESOURCES.map((resource) => resource.id))
  const organId = input.tags?.find((tag) => resourceIds.has(tag))
  const organResource = ANATOMY_RESOURCES.find((resource) => resource.id === organId)
  const hasSkinModel = preciseSkinTopics.has(input.id) && skinResource?.model
  const modelResource = hasSkinModel ? skinResource : organResource
  const hasModel = Boolean(modelResource?.model)
  return {
    id: `${input.id}-overview`,
    title: input.location,
    anchorIds: hasSkinModel ? ['epidermis'] : [],
    viewType: input.viewType || 'OVERVIEW',
    description: input.mechanism,
    displayOrder: 1,
    modelRef: hasModel ? modelResource.model : null,
    modelAvailability: hasModel ? 'AVAILABLE' : 'PLANNED',
    leaderLines: hasSkinModel ? [{ anchorId: 'epidermis', label: input.location, effect: input.mechanism }] : [],
  }
}

function specialDisplayUnits(input) {
  const skinResource = ANATOMY_RESOURCES.find((resource) => resource.id === 'skin')
  const liverResource = ANATOMY_RESOURCES.find((resource) => resource.id === 'liver')
  if (input.id === 'hand-foot-mouth') return [
    ['mouth', t('口腔黏膜', 'Oral mucosa')],
    ['palm', t('手掌', 'Palms')],
    ['sole', t('足底', 'Soles')],
  ].map(([id, title], index) => ({
    id: `hand-foot-mouth-${id}`,
    title,
    anchorIds: [],
    viewType: 'SURFACE_MAP',
    description: input.mechanism,
    displayOrder: index + 1,
    modelRef: id === 'mouth' ? null : skinResource?.model || null,
    modelAvailability: id === 'mouth' || !skinResource?.model ? 'PLANNED' : 'AVAILABLE',
    leaderLines: [],
  }))
  if (input.id === 'newborn-jaundice') return [
    { id: 'newborn-jaundice-surface', title: t('皮肤与巩膜黄染', 'Yellow skin and sclera'), anchorIds: [], viewType: 'SURFACE_MAP', description: t('这是家长可观察的表现层，不代表病因位于皮肤。', 'This is the visible layer and does not mean the cause is in the skin.'), displayOrder: 1, modelRef: skinResource?.model || null, modelAvailability: skinResource?.model ? 'AVAILABLE' : 'PLANNED', leaderLines: [] },
    { id: 'newborn-jaundice-pathway', title: t('胆红素产生、肝脏处理与排泄', 'Bilirubin production, liver processing and excretion'), anchorIds: [], viewType: 'PATHWAY', description: input.mechanism, displayOrder: 2, modelRef: liverResource?.model || null, modelAvailability: liverResource?.model ? 'AVAILABLE' : 'PLANNED', leaderLines: [] },
  ]
  return null
}

function defineDisease(input) {
  const profile = PROFILES[input.profile]
  const symptoms = items(input.symptoms[0], input.symptoms[1])
  const displayUnits = input.displayUnits || specialDisplayUnits(input) || [defaultDisplayUnit(input)]
  return Object.freeze({
    id: input.id,
    name: input.name,
    aliases: items(input.aliases?.[0] || '', input.aliases?.[1] || '').filter((item) => item.zh),
    ageRange: { minDays: input.age[0], maxDays: input.age[1], label: input.age[2] },
    category: CATEGORIES[input.profile],
    categoryTags: input.tags || [input.profile],
    shortDefinition: input.definition,
    quickTake: {
      location: input.location,
      mechanism: input.mechanism,
      typicalSigns: symptoms.slice(0, 3),
      course: input.course,
      watch: profile.observation[0],
      department: input.department,
    },
    anatomyBinding: {
      diseaseId: input.id,
      anatomyAnchors: displayUnits.flatMap((unit) => unit.anchorIds),
      primaryAnchor: displayUnits[0]?.anchorIds[0] || null,
      locationType: input.locationType || 'FOCAL',
      displayUnits,
      modelAvailability: displayUnits.some((unit) => unit.modelAvailability === 'AVAILABLE') ? 'AVAILABLE' : 'PLANNED',
    },
    causes: [input.cause],
    triggers: input.triggers || [],
    riskFactors: input.riskFactors || [],
    transmission: input.transmission || null,
    mechanismSteps: [t('正常结构与功能', 'Normal structure and function'), input.cause, input.mechanism, symptoms[0]],
    impacts: input.impacts || symptoms.slice(0, 3),
    commonSymptoms: symptoms,
    diseaseCourse: input.course,
    observationGuidance: profile.observation,
    generalManagement: profile.management,
    homeCareGuidance: profile.homeCare,
    avoidActions: profile.avoid,
    careDepartment: { primary: input.department, fallback: t('儿科；紧急情况进入儿童急诊或急诊', 'Pediatrics; use pediatric emergency or emergency care when urgent') },
    carePreparation: DEFAULT_PREPARATION,
    prevention: profile.prevention,
    escalationRuleRef: input.escalationRuleRef || 'decision-unit:general_health_preassessment',
    sourceRefs: (input.sourceIds || ['aapCommon']).map((id) => DISEASE_SOURCES[id]),
    status: 'PUBLISHED',
    version: DISEASE_CONTENT_VERSION,
    review: { status: 'SOURCE_CHECKED', lastReviewedAt: '2026-08-08', knownLimitations: t('通用家庭教育内容，不用于诊断、分级或个体化处方。', 'General family education only; not for diagnosis, triage or individualized prescriptions.') },
  })
}

const age = {
  all: [0, 2191, t('0–6 岁', '0–6 years')],
  infant: [0, 730, t('婴儿期更常见', 'More common in infancy')],
  newborn: [0, 28, t('新生儿期', 'Newborn period')],
  toddler: [180, 2191, t('婴幼儿与学龄前期', 'Infant, toddler and preschool years')],
}

const D = defineDisease

export const DISEASE_TOPICS = [
  D({ id: 'newborn-jaundice', name: t('新生儿黄疸', 'Newborn jaundice'), aliases: ['黄疸', 'Jaundice'], age: age.newborn, profile: 'newborn', location: t('皮肤、巩膜与胆红素处理通路', 'Skin, sclera and bilirubin pathway'), definition: t('新生儿血中胆红素升高后出现皮肤或巩膜黄染的表现，需要结合日龄、喂养和测量判断原因。', 'Yellow skin or sclera caused by raised bilirubin in a newborn; timing, feeding and measurement are needed to assess the cause.'), cause: t('胆红素产生较多、肝脏处理与排泄尚未成熟，或存在溶血、感染、喂养和胆道问题。', 'Higher bilirubin production, immature processing and excretion, or hemolysis, infection, feeding and biliary problems.'), mechanism: t('胆红素产生后经肝脏处理并随胆汁排出；任一环节负荷增加或受阻都可使胆红素累积。', 'Bilirubin is processed by the liver and excreted in bile; increased load or obstruction at any step can cause accumulation.'), symptoms: ['皮肤或眼白发黄|吃奶或精神状态变化|尿便颜色变化', 'Yellow skin or eyes|Feeding or alertness change|Urine or stool color change'], course: t('许多生理性黄疸在出生数日出现后逐渐消退，但出现时间早、持续或加深时需按专业计划复查。', 'Many physiologic cases appear after the first days and fade, but early, persistent or deepening jaundice needs planned clinical review.'), department: t('儿科或新生儿科', 'Pediatrics or neonatology'), sourceIds: ['whoChild', 'nhsChildren'], locationType: 'PATHWAY', escalationRuleRef: 'decision-unit:jaundice_observation' }),
  D({ id: 'omphalitis', name: t('新生儿脐炎', 'Omphalitis'), aliases: ['肚脐感染', 'Umbilical infection'], age: age.newborn, profile: 'newborn', location: t('脐部残端及周围皮肤', 'Umbilical stump and surrounding skin'), definition: t('脐残端及周围组织的感染或炎症，新生儿期需要及时评估。', 'Infection or inflammation of the umbilical stump and nearby tissue that needs prompt newborn assessment.'), cause: t('细菌经未愈合脐部进入组织，潮湿、污染或护理不当可增加风险。', 'Bacteria enter through the healing stump; moisture, contamination or unsafe care can increase risk.'), mechanism: t('局部感染可从脐部向周围皮肤和深部组织扩展。', 'Local infection can spread from the stump into surrounding skin and deeper tissue.'), symptoms: ['脐周红肿或发热|脓性或异味分泌物|吃奶或精神变差', 'Redness or warmth around the navel|Pus or foul discharge|Reduced feeding or alertness'], course: t('轻微残端渗液与感染需要区分；红肿扩展或全身状态变化不能等待自行好转。', 'Minor stump moisture must be distinguished from infection; spreading redness or systemic change should not be watched at home.'), department: t('新生儿科或儿科', 'Neonatology or pediatrics'), sourceIds: ['whoChild'] }),
  D({ id: 'oral-thrush', name: t('鹅口疮', 'Oral thrush'), aliases: ['口腔念珠菌病', 'Oral candidiasis'], age: age.infant, profile: 'newborn', location: t('舌、颊黏膜和口腔表面', 'Tongue, inner cheeks and oral mucosa'), definition: t('念珠菌在口腔黏膜过度生长形成不易擦掉的白色斑片。', 'Candida overgrowth on oral mucosa causing white patches that do not wipe away easily.'), cause: t('婴儿口腔菌群和免疫仍在发育，抗生素暴露或哺乳相关交叉感染可增加风险。', 'Developing oral flora and immunity, antibiotic exposure or feeding-related cross-infection can increase risk.'), mechanism: t('真菌附着黏膜并引起表浅炎症，疼痛时可能影响吸吮和进食。', 'Yeast adheres to mucosa and causes superficial inflammation that can make sucking and feeding painful.'), symptoms: ['口腔白色斑片|吃奶时不适或哭闹|乳母乳头疼痛或反复感染', 'White oral patches|Discomfort or crying during feeds|Maternal nipple pain or recurrent infection'], course: t('规范治疗和清洁后通常改善；反复、广泛或影响进食时需复诊。', 'Usually improves with prescribed treatment and hygiene; recurrent, extensive or feeding-limiting disease needs review.'), department: t('儿科或儿童口腔科', 'Pediatrics or pediatric dentistry'), sourceIds: ['nhsChildren'] }),
  D({ id: 'infant-reflux', name: t('婴儿胃食管反流', 'Infant gastroesophageal reflux'), aliases: ['婴儿吐奶|生理性反流', 'Spit-up|Physiologic reflux'], age: age.infant, profile: 'digestive', location: t('胃与食管连接处', 'Junction of stomach and esophagus'), definition: t('胃内容物返回食管或口腔的常见婴儿现象；只有伴生长、疼痛或呼吸问题时才考虑疾病性反流。', 'Common return of stomach contents into the esophagus or mouth; disease is considered when growth, pain or breathing are affected.'), cause: t('下食管括约肌尚未成熟、液体饮食和较多平卧时间共同促成反流。', 'An immature lower esophageal sphincter, liquid diet and frequent lying down contribute.'), mechanism: t('胃内容物短暂越过括约肌向上移动，可表现为溢奶或吐奶。', 'Stomach contents briefly move upward across the sphincter, causing spit-up.'), symptoms: ['喂后溢奶或吐奶|喂养不适|伴随体重增长或呼吸问题时需评估', 'Spit-up after feeds|Feeding discomfort|Growth or breathing concerns need assessment'], course: t('多数随坐立增加和消化道成熟在婴儿期逐渐减少。', 'Most cases decrease during infancy as upright time and digestive maturity increase.'), department: t('儿科或儿童消化科', 'Pediatrics or pediatric gastroenterology'), sourceIds: ['nhsChildren'] }),
  D({ id: 'atopic-dermatitis', name: t('特应性皮炎', 'Atopic dermatitis'), aliases: ['婴儿湿疹|湿疹', 'Infant eczema|Eczema'], age: age.all, profile: 'skin', location: t('皮肤屏障，婴儿常见于面颊和伸侧', 'Skin barrier, often cheeks and extensor surfaces in infants'), definition: t('反复干燥、发红和瘙痒的慢性炎症性皮肤病。', 'A chronic inflammatory skin condition with recurrent dryness, redness and itch.'), cause: t('皮肤屏障脆弱与免疫反应共同作用，干燥、热、摩擦和刺激物可诱发。', 'Skin-barrier weakness and immune responses interact; dryness, heat, friction and irritants may trigger flares.'), mechanism: t('屏障失水和炎症形成瘙痒抓挠循环，破损后更易继发感染。', 'Barrier water loss and inflammation create an itch-scratch cycle; broken skin is more prone to infection.'), symptoms: ['干燥粗糙和红斑|明显瘙痒|渗液、结痂或皮肤增厚', 'Dry rough red skin|Marked itch|Weeping, crusting or thickening'], course: t('常反复波动，需要持续屏障护理并按复发程度复诊调整方案。', 'Often waxes and wanes, requiring ongoing barrier care and review when flares change.'), department: t('儿科或儿童皮肤科', 'Pediatrics or pediatric dermatology'), sourceIds: ['nhsSkin'] }),
  D({ id: 'diaper-dermatitis', name: t('尿布疹', 'Diaper dermatitis'), aliases: ['尿布皮炎|红屁股', 'Diaper rash'], age: age.infant, profile: 'skin', location: t('尿布覆盖的皮肤表面与皱褶', 'Skin and folds within the diaper area'), definition: t('尿液、粪便、潮湿和摩擦造成的尿布区刺激性皮炎，可合并真菌感染。', 'Irritant dermatitis from urine, stool, moisture and friction, sometimes with secondary yeast infection.'), cause: t('皮肤长时间潮湿并接触排泄物，腹泻或更换不及时会增加刺激。', 'Prolonged moisture and contact with waste irritate skin; diarrhea and infrequent changes increase risk.'), mechanism: t('屏障受损后出现红斑和疼痛，念珠菌可在温暖潮湿环境继发增殖。', 'Barrier damage causes redness and pain; Candida may overgrow in the warm moist area.'), symptoms: ['尿布区红斑和疼痛|擦拭或排便时哭闹|皱褶内卫星样红点提示真菌可能', 'Red painful diaper-area skin|Crying during wiping or stooling|Satellite spots in folds may suggest yeast'], course: t('减少刺激和加强屏障护理后多较快改善；破溃、扩散或持续不改善需评估。', 'Often improves quickly with less irritation and barrier care; broken, spreading or persistent rash needs review.'), department: t('儿科或儿童皮肤科', 'Pediatrics or pediatric dermatology'), sourceIds: ['nhsChildren'] }),
  D({ id: 'blocked-tear-duct', name: t('泪道阻塞', 'Blocked tear duct'), aliases: ['鼻泪管阻塞|泪囊炎', 'Nasolacrimal duct obstruction|Dacryocystitis'], age: age.infant, profile: 'eye', location: t('泪囊与鼻泪管', 'Lacrimal sac and nasolacrimal duct'), definition: t('婴儿鼻泪管未完全开放导致流泪和分泌物；红肿疼痛时需排除感染。', 'Incomplete opening of an infant tear duct causing tearing and discharge; painful redness may indicate infection.'), cause: t('出生后鼻泪管末端膜性结构尚未开放最常见。', 'A membrane at the lower tear duct remaining closed after birth is the common cause.'), mechanism: t('泪液排入鼻腔受阻后在眼角积聚，继发细菌繁殖时分泌物增多。', 'Blocked drainage pools tears at the inner eye; secondary bacterial growth can increase discharge.'), symptoms: ['持续流泪|眼角黏性分泌物|泪囊区红肿需及时评估', 'Persistent tearing|Sticky inner-corner discharge|Red swollen tear-sac area needs prompt review'], course: t('多数在婴儿期随泪道发育自行开放；持续或感染时需专科评估。', 'Most open spontaneously during infancy; persistence or infection needs specialist assessment.'), department: t('儿科或儿童眼科', 'Pediatrics or pediatric ophthalmology'), sourceIds: ['nhsChildren'] }),
  D({ id: 'common-cold', name: t('普通感冒', 'Common cold'), aliases: ['急性上呼吸道感染|上感', 'Acute upper respiratory infection|URI'], age: age.all, profile: 'respiratory', tags: ['respiratory', 'lungs'], location: t('鼻腔、咽喉和上呼吸道', 'Nose, throat and upper airway'), definition: t('多种呼吸道病毒引起的轻型上呼吸道感染。', 'A mild upper-airway infection caused by many respiratory viruses.'), cause: t('鼻病毒等多种病毒经飞沫、空气或接触传播。', 'Rhinoviruses and many other viruses spread through air, droplets and contact.'), mechanism: t('病毒使鼻咽黏膜发炎并增加分泌物，引起鼻塞、流涕和咳嗽。', 'Viral inflammation of the nose and throat increases mucus, causing congestion, runny nose and cough.'), symptoms: ['流涕和鼻塞|咳嗽或咽部不适|可有低热和食欲下降', 'Runny or blocked nose|Cough or sore throat|Possible low fever and reduced appetite'], course: t('症状常在数日内最明显，咳嗽和鼻涕可持续一至两周并逐步改善。', 'Symptoms often peak over several days; cough and nasal discharge can last one to two weeks while improving.'), department: t('儿科', 'Pediatrics'), transmission: t('呼吸道飞沫、空气和被污染的手或物品。', 'Respiratory droplets, air and contaminated hands or objects.'), sourceIds: ['aapCommon', 'nhsChildren'] }),
  D({ id: 'influenza', name: t('流感', 'Influenza'), aliases: ['流行性感冒', 'Flu'], age: age.all, profile: 'respiratory', tags: ['respiratory', 'lungs', 'infectious'], location: t('呼吸道，可伴全身反应', 'Respiratory tract with systemic effects'), definition: t('流感病毒引起的急性呼吸道传染病，通常比普通感冒起病更急、全身症状更明显。', 'An acute contagious respiratory illness caused by influenza viruses, often more sudden and systemic than a cold.'), cause: t('甲型或乙型流感病毒感染。', 'Influenza A or B virus infection.'), mechanism: t('病毒感染呼吸道上皮并触发全身炎症反应。', 'The virus infects respiratory epithelium and triggers a systemic inflammatory response.'), symptoms: ['突然发热|咳嗽和咽痛|乏力、肌痛或食欲下降', 'Sudden fever|Cough and sore throat|Fatigue, aches or reduced appetite'], course: t('多在数日内达到高峰后改善，幼儿和有基础病儿童并发症风险更高。', 'Often peaks over several days then improves; young children and those with chronic conditions have higher complication risk.'), department: t('儿科或儿童感染科', 'Pediatrics or pediatric infectious disease'), transmission: t('主要经空气、飞沫和密切接触传播。', 'Mainly through air, droplets and close contact.'), sourceIds: ['cdcRespiratory', 'cdcVaccines'] }),
  D({ id: 'covid-19', name: t('COVID-19', 'COVID-19'), aliases: ['新冠|新型冠状病毒感染', 'COVID|Coronavirus disease'], age: age.all, profile: 'respiratory', tags: ['respiratory', 'lungs', 'infectious'], location: t('上呼吸道，部分病例影响下呼吸道或全身', 'Upper airway; some cases affect lower airways or other systems'), definition: t('SARS-CoV-2 引起的传染性疾病，儿童表现可从无症状到发热、呼吸道或胃肠道症状。', 'A contagious illness caused by SARS-CoV-2, ranging in children from no symptoms to respiratory, fever or gastrointestinal illness.'), cause: t('SARS-CoV-2 感染。', 'SARS-CoV-2 infection.'), mechanism: t('病毒感染呼吸道细胞并引起免疫反应，但不能把所有儿童都表达成固定肺部病灶。', 'The virus infects respiratory cells and triggers immune responses; children should not be depicted as all having a fixed lung lesion.'), symptoms: ['发热、咳嗽或鼻咽症状|乏力或胃肠道症状|部分儿童无明显症状', 'Fever, cough or nasal symptoms|Fatigue or gastrointestinal symptoms|Some children have few or no symptoms'], course: t('多数儿童为轻症并逐步恢复；持续或加重及感染后新症状需要评估。', 'Most children have mild illness and recover; persistent, worsening or new post-infection symptoms need assessment.'), department: t('儿科或儿童感染科', 'Pediatrics or pediatric infectious disease'), transmission: t('主要经空气和近距离呼吸道颗粒传播。', 'Mainly through airborne and close-range respiratory particles.'), sourceIds: ['cdcRespiratory', 'cdcVaccines'] }),
  D({ id: 'rsv-infection', name: t('RSV 感染', 'RSV infection'), aliases: ['呼吸道合胞病毒感染', 'Respiratory syncytial virus infection'], age: age.all, profile: 'respiratory', tags: ['respiratory', 'lungs', 'infectious'], location: t('鼻咽和气道，婴儿可累及细支气管', 'Nose and airway; bronchioles may be affected in infants'), definition: t('呼吸道合胞病毒引起的常见感染，婴儿可能发展为毛细支气管炎或肺炎。', 'A common respiratory syncytial virus infection that may cause bronchiolitis or pneumonia in infants.'), cause: t('呼吸道合胞病毒感染。', 'Respiratory syncytial virus infection.'), mechanism: t('病毒使呼吸道黏膜发炎并增加分泌物，小婴儿较细的气道更易受影响。', 'Viral inflammation and mucus affect the airway; infants have narrower airways that obstruct more easily.'), symptoms: ['流涕和咳嗽|喘鸣或呼吸费力|吃奶减少', 'Runny nose and cough|Wheeze or labored breathing|Reduced feeding'], course: t('常从上呼吸道症状开始，数日内可能加重后逐步恢复。', 'Often starts with upper-airway symptoms, may worsen over several days, then gradually recover.'), department: t('儿科或儿童呼吸科', 'Pediatrics or pediatric respiratory medicine'), transmission: t('呼吸道飞沫、密切接触和污染表面。', 'Respiratory droplets, close contact and contaminated surfaces.'), sourceIds: ['cdcRespiratory', 'cdcVaccines'] }),
  D({ id: 'bronchiolitis', name: t('毛细支气管炎', 'Bronchiolitis'), aliases: ['细支气管炎', 'Small-airway infection'], age: age.infant, profile: 'respiratory', tags: ['respiratory', 'lungs'], location: t('末端细支气管管壁、分泌物和管腔', 'Walls, mucus and lumen of terminal bronchioles'), definition: t('婴幼儿常见的病毒性小气道炎症，以咳嗽、喘鸣和呼吸费力为主要表现。', 'A common viral small-airway illness in infants and young children, with cough, wheeze and increased breathing effort.'), cause: t('RSV 最常见，也可由其他呼吸道病毒引起。', 'RSV is most common, with other respiratory viruses also causing it.'), mechanism: t('小气道管壁肿胀、分泌物增加并使管腔变窄，空气通过更困难。', 'Swollen small-airway walls and increased mucus narrow the lumen and make airflow harder.'), symptoms: ['咳嗽和喘鸣|呼吸增快或费力|吃奶和睡眠受影响', 'Cough and wheeze|Faster or labored breathing|Feeding and sleep affected'], course: t('常在起病数日后呼吸症状更明显，再逐步改善；咳嗽可能持续更久。', 'Breathing symptoms often become more obvious after several days and then improve; cough may last longer.'), department: t('儿科或儿童呼吸科', 'Pediatrics or pediatric respiratory medicine'), transmission: t('取决于致病病毒，常经呼吸道和接触传播。', 'Depends on the virus, commonly respiratory and contact spread.'), sourceIds: ['aapCommon', 'cdcRespiratory'] }),
  D({ id: 'acute-bronchitis', name: t('急性支气管炎', 'Acute bronchitis'), aliases: ['支气管炎', 'Bronchitis'], age: age.all, profile: 'respiratory', tags: ['respiratory', 'lungs'], location: t('较大的支气管', 'Larger bronchi'), definition: t('多由病毒造成的支气管急性炎症，主要表现为咳嗽。', 'Acute inflammation of the larger bronchi, usually viral and mainly causing cough.'), cause: t('多数由呼吸道病毒感染引起。', 'Most cases are caused by respiratory viruses.'), mechanism: t('支气管黏膜发炎并分泌黏液，刺激咳嗽反射。', 'Inflamed bronchial lining and mucus stimulate the cough reflex.'), symptoms: ['持续咳嗽|可有痰鸣或胸部不适|常伴前期感冒症状', 'Persistent cough|Possible noisy mucus or chest discomfort|Often follows cold symptoms'], course: t('全身症状先改善，咳嗽可能持续数周；反复或呼吸困难需重新评估。', 'Systemic symptoms improve first while cough may last weeks; recurrence or breathing difficulty needs reassessment.'), department: t('儿科', 'Pediatrics'), sourceIds: ['aapCommon'] }),
  D({ id: 'pneumonia', name: t('肺炎', 'Pneumonia'), aliases: ['小儿肺炎', 'Childhood pneumonia'], age: age.all, profile: 'respiratory', tags: ['respiratory', 'lungs'], location: t('肺实质和肺泡区域', 'Lung tissue and alveoli'), definition: t('感染引起肺组织炎症并影响通气和气体交换。', 'An infection that inflames lung tissue and affects ventilation and gas exchange.'), cause: t('可由病毒、细菌或较少见的其他病原体引起。', 'Can be caused by viruses, bacteria or less common pathogens.'), mechanism: t('肺泡和周围组织出现炎症及液体，氧气交换效率下降。', 'Inflammation and fluid in and around alveoli reduce oxygen exchange.'), symptoms: ['发热和咳嗽|呼吸增快或费力|精神或进食变差', 'Fever and cough|Faster or labored breathing|Reduced alertness or intake'], course: t('病程取决于病因与严重程度；呼吸状态和总体趋势比单个症状更重要。', 'Course depends on cause and severity; breathing and overall trend matter more than one symptom.'), department: t('儿科或儿童呼吸科', 'Pediatrics or pediatric respiratory medicine'), transmission: t('病原体传播方式不同，多数呼吸道病原经空气、飞沫或接触传播。', 'Spread depends on the pathogen; many respiratory causes spread through air, droplets or contact.'), sourceIds: ['whoPneumonia'] }),
  D({ id: 'croup', name: t('哮吼', 'Croup'), aliases: ['急性喉炎|喉气管炎', 'Acute laryngitis|Laryngotracheitis'], age: age.toddler, profile: 'respiratory', tags: ['respiratory', 'throat'], location: t('喉部与声门下气道', 'Larynx and subglottic airway'), definition: t('多由病毒引起的上气道炎症，产生犬吠样咳嗽和吸气性喉鸣。', 'Usually viral upper-airway inflammation causing a barking cough and inspiratory stridor.'), cause: t('副流感病毒等呼吸道病毒最常见。', 'Parainfluenza and other respiratory viruses are common causes.'), mechanism: t('声门下黏膜肿胀使儿童本就较窄的上气道进一步变窄。', 'Subglottic swelling further narrows a child\'s already small upper airway.'), symptoms: ['犬吠样咳嗽|声音嘶哑|吸气时喉鸣', 'Barking cough|Hoarse voice|Noisy breathing in'], course: t('常夜间更明显，数日内逐步改善；安静时仍有喉鸣需及时评估。', 'Often worse at night and improves over days; stridor while calm needs prompt assessment.'), department: t('儿科、儿童呼吸科或急诊', 'Pediatrics, pediatric respiratory medicine or emergency care'), transmission: t('致病病毒通常经呼吸道传播。', 'The causative viruses usually spread through the respiratory route.'), sourceIds: ['nhsChildren'] }),
  D({ id: 'pertussis', name: t('百日咳', 'Pertussis'), aliases: ['百日咳杆菌感染', 'Whooping cough'], age: age.all, profile: 'respiratory', tags: ['respiratory', 'infectious'], location: t('气管与支气管', 'Trachea and bronchi'), definition: t('百日咳鲍特菌引起的高度传染性呼吸道感染，婴儿可能不出现典型鸡鸣样回声。', 'A highly contagious Bordetella pertussis infection; infants may not have the classic whoop.'), cause: t('百日咳鲍特菌感染。', 'Bordetella pertussis infection.'), mechanism: t('细菌毒素损伤气道纤毛并引发阵发性剧烈咳嗽。', 'Bacterial toxins damage airway cilia and trigger severe coughing fits.'), symptoms: ['阵发性连续咳嗽|咳后呕吐或吸气回声|婴儿可出现呼吸暂停', 'Paroxysmal coughing fits|Post-cough vomiting or whoop|Infants may have pauses in breathing'], course: t('咳嗽可持续数周并分阶段变化，婴儿并发症风险更高。', 'Cough can last for weeks in stages; infants have greater complication risk.'), department: t('儿科或儿童感染科', 'Pediatrics or pediatric infectious disease'), transmission: t('主要经近距离呼吸道飞沫传播。', 'Mainly through close-range respiratory droplets.'), sourceIds: ['cdcVaccines'] }),
  D({ id: 'childhood-asthma', name: t('儿童哮喘', 'Childhood asthma'), aliases: ['喘息性疾病|反复喘息', 'Wheezing illness|Recurrent wheeze'], age: age.toddler, profile: 'respiratory', tags: ['respiratory', 'lungs'], location: t('支气管平滑肌、黏膜与管腔', 'Bronchial smooth muscle, lining and lumen'), definition: t('气道慢性炎症和可变性狭窄导致反复喘鸣、咳嗽或呼吸困难。', 'Chronic airway inflammation and variable narrowing causing recurrent wheeze, cough or breathlessness.'), cause: t('遗传易感性与病毒、过敏原、烟雾或运动等触发因素共同作用。', 'Genetic susceptibility interacts with viruses, allergens, smoke, exercise and other triggers.'), mechanism: t('气道炎症、平滑肌收缩和黏液增加使管腔暂时变窄。', 'Inflammation, smooth-muscle tightening and mucus temporarily narrow the airway.'), symptoms: ['反复喘鸣|夜间或运动后咳嗽|胸闷或呼吸费力', 'Recurrent wheeze|Night or exercise-related cough|Chest tightness or breathlessness'], course: t('症状呈发作和缓解交替，需要按专业计划识别触发因素并长期复查。', 'Symptoms alternate between flares and relief, requiring a clinician-led trigger and follow-up plan.'), department: t('儿科、儿童呼吸科或过敏专科', 'Pediatrics, pediatric respiratory or allergy medicine'), sourceIds: ['nhsChildren'] }),
  D({ id: 'allergic-rhinitis', name: t('过敏性鼻炎', 'Allergic rhinitis'), aliases: ['鼻过敏|花粉症', 'Nasal allergy|Hay fever'], age: age.toddler, profile: 'respiratory', tags: ['respiratory', 'nose'], location: t('鼻腔黏膜', 'Nasal mucosa'), definition: t('吸入过敏原引起的鼻黏膜免疫反应，表现为喷嚏、清涕和鼻痒。', 'An immune reaction in nasal mucosa to inhaled allergens, causing sneezing, clear discharge and itch.'), cause: t('花粉、尘螨、动物皮屑或霉菌等过敏原。', 'Allergens such as pollen, dust mites, animal dander or mold.'), mechanism: t('过敏反应使鼻黏膜肿胀并增加清水样分泌物。', 'Allergic inflammation swells nasal mucosa and increases watery secretions.'), symptoms: ['连续喷嚏和清涕|鼻痒或揉鼻|鼻塞影响睡眠', 'Repeated sneezing and clear discharge|Nasal itch or rubbing|Congestion affecting sleep'], course: t('可随季节或暴露反复，减少触发和规范治疗可控制症状。', 'May recur by season or exposure; trigger reduction and planned treatment can control symptoms.'), department: t('儿科、儿童耳鼻喉科或过敏专科', 'Pediatrics, pediatric ENT or allergy medicine'), sourceIds: ['nhsChildren'] }),
  D({ id: 'hand-foot-mouth', name: t('手足口病', 'Hand, foot and mouth disease'), aliases: ['手足口', 'HFMD'], age: age.toddler, profile: 'infectious', tags: ['infectious', 'skin', 'mouth'], location: t('口腔黏膜、手掌、足底及其他皮肤表面', 'Oral mucosa, palms, soles and other skin surfaces'), definition: t('肠道病毒引起的常见传染病，典型表现为发热、口腔疱疹或溃疡和手足皮疹。', 'A common enterovirus illness with fever, mouth sores and a rash on hands and feet.'), cause: t('柯萨奇病毒等肠道病毒感染。', 'Coxsackieviruses and other enteroviruses.'), mechanism: t('病毒在口咽和肠道复制后引起黏膜与皮肤的多部位病变。', 'Virus replicates in the oropharynx and gut, then causes lesions at multiple mucosal and skin sites.'), symptoms: ['发热|口腔疱疹或溃疡|手掌、足底皮疹和进食不适', 'Fever|Mouth blisters or ulcers|Palm and sole rash with feeding discomfort'], course: t('多数在七至十天内自行改善，口腔疼痛期间需重点观察饮水和尿量。', 'Most improve within seven to ten days; fluids and urine need close observation while mouth sores hurt.'), department: t('儿科或儿童感染科', 'Pediatrics or pediatric infectious disease'), transmission: t('经呼吸道分泌物、疱疹液、粪口途径和污染表面传播。', 'Through respiratory secretions, blister fluid, fecal-oral spread and contaminated surfaces.'), sourceIds: ['cdcHfmd'] }),
  D({ id: 'roseola', name: t('幼儿急疹', 'Roseola'), aliases: ['婴儿玫瑰疹', 'Sixth disease'], age: age.toddler, profile: 'infectious', tags: ['infectious', 'skin'], location: t('全身反应与躯干皮肤', 'Systemic response and trunk skin'), definition: t('人疱疹病毒引起的幼儿常见感染，常先高热，退热后出现躯干皮疹。', 'A common herpesvirus illness in young children, often with high fever followed by a trunk rash as fever resolves.'), cause: t('人疱疹病毒 6 或 7 型感染。', 'Human herpesvirus 6 or 7 infection.'), mechanism: t('病毒先引起全身发热反应，免疫反应阶段出现短暂皮疹。', 'The virus first causes systemic fever, followed by a brief immune-related rash.'), symptoms: ['数日发热|退热后躯干淡红疹|可伴轻微上呼吸道症状', 'Several days of fever|Pink trunk rash after fever falls|Possible mild respiratory symptoms'], course: t('皮疹通常短暂并自行消退；发热期间重点观察精神和液体摄入。', 'The rash is usually brief and self-limited; alertness and fluids matter during fever.'), department: t('儿科', 'Pediatrics'), transmission: t('主要通过唾液和密切接触传播。', 'Mainly through saliva and close contact.'), sourceIds: ['nhsChildren'] }),
  D({ id: 'chickenpox', name: t('水痘', 'Chickenpox'), aliases: ['水痘-带状疱疹病毒感染', 'Varicella'], age: age.all, profile: 'infectious', tags: ['infectious', 'skin'], location: t('全身皮肤表面', 'Skin surfaces across the body'), definition: t('水痘-带状疱疹病毒引起的传染病，出现分批、不同阶段的瘙痒性疱疹。', 'A varicella-zoster virus illness with itchy crops of lesions at different stages.'), cause: t('水痘-带状疱疹病毒初次感染。', 'Primary varicella-zoster virus infection.'), mechanism: t('病毒经呼吸道进入后扩散至皮肤，形成红斑、丘疹、水疱和结痂。', 'After respiratory entry, virus spreads to skin, forming spots, bumps, blisters and crusts.'), symptoms: ['发热和不适|分批出现瘙痒性水疱|头皮和躯干常较多', 'Fever and malaise|Itchy crops of blisters|Often prominent on scalp and trunk'], course: t('新疹可持续数日，全部结痂后逐步恢复；抓破后可能继发感染。', 'New lesions may appear for days and recovery follows crusting; scratching can cause secondary infection.'), department: t('儿科或儿童感染科', 'Pediatrics or pediatric infectious disease'), transmission: t('经空气、呼吸道分泌物和疱疹液传播。', 'Through air, respiratory secretions and blister fluid.'), sourceIds: ['cdcVaccines'] }),
  D({ id: 'scarlet-fever', name: t('猩红热', 'Scarlet fever'), aliases: ['A组链球菌猩红热', 'Group A strep scarlet fever'], age: age.toddler, profile: 'infectious', tags: ['infectious', 'skin', 'throat'], location: t('咽喉与全身皮肤', 'Throat and widespread skin'), definition: t('产毒素的 A 组链球菌感染引起咽炎和细砂纸样皮疹。', 'Toxin-producing group A streptococcal infection causing pharyngitis and a sandpaper-like rash.'), cause: t('产红疹毒素的 A 组链球菌感染。', 'Toxigenic group A streptococcal infection.'), mechanism: t('咽部细菌感染释放毒素，引起弥漫性皮肤红疹。', 'Throat infection releases toxin that causes a diffuse red rash.'), symptoms: ['发热和咽痛|细砂纸样红疹|草莓舌或颈部淋巴结肿大', 'Fever and sore throat|Fine sandpaper rash|Strawberry tongue or swollen neck nodes'], course: t('规范抗感染治疗后通常改善，需要完成专业人员制定的疗程。', 'Usually improves with prescribed antimicrobial treatment, which must be completed as directed.'), department: t('儿科或儿童感染科', 'Pediatrics or pediatric infectious disease'), transmission: t('主要经呼吸道飞沫和密切接触传播。', 'Mainly through respiratory droplets and close contact.'), sourceIds: ['nhsChildren'] }),
  D({ id: 'measles', name: t('麻疹', 'Measles'), aliases: ['麻疹病毒感染', 'Rubeola'], age: age.all, profile: 'infectious', tags: ['infectious', 'skin', 'respiratory'], location: t('呼吸道、全身和皮肤', 'Respiratory tract, systemic tissues and skin'), definition: t('麻疹病毒引起的高度传染性疾病，表现为发热、咳嗽、眼红和扩散性皮疹。', 'A highly contagious measles virus illness with fever, cough, red eyes and a spreading rash.'), cause: t('麻疹病毒感染。', 'Measles virus infection.'), mechanism: t('病毒由呼吸道进入并全身扩散，免疫反应形成典型皮疹。', 'Virus enters through the respiratory tract and spreads systemically; immune response creates the rash.'), symptoms: ['高热、咳嗽和流涕|眼红或畏光|从头面向下扩展的皮疹', 'High fever, cough and coryza|Red or light-sensitive eyes|Rash spreading downward from face'], course: t('可出现肺炎等并发症，疑似病例应先电话联系医疗机构并避免候诊区暴露。', 'Complications such as pneumonia can occur; suspected cases should call ahead and avoid exposing waiting rooms.'), department: t('儿科或儿童感染科', 'Pediatrics or pediatric infectious disease'), transmission: t('通过空气传播，传染性很强。', 'Airborne and highly contagious.'), sourceIds: ['cdcVaccines'] }),
  D({ id: 'mumps', name: t('腮腺炎', 'Mumps'), aliases: ['流行性腮腺炎', 'Epidemic parotitis'], age: age.all, profile: 'infectious', tags: ['infectious', 'mouth'], location: t('耳下腮腺及唾液腺', 'Parotid and other salivary glands'), definition: t('腮腺炎病毒引起的传染病，常见耳下或下颌部肿痛。', 'A mumps virus illness commonly causing painful swelling below the ear or jaw.'), cause: t('腮腺炎病毒感染。', 'Mumps virus infection.'), mechanism: t('病毒感染唾液腺并引起腮腺炎症肿胀。', 'Virus infects salivary glands and inflames the parotid.'), symptoms: ['耳下或下颌肿痛|发热和乏力|咀嚼或吞咽不适', 'Painful swelling below ear or jaw|Fever and fatigue|Discomfort chewing or swallowing'], course: t('多数逐步恢复，但出现剧烈头痛、颈强或其他部位疼痛需评估并发症。', 'Most recover gradually; severe headache, stiff neck or pain elsewhere needs complication assessment.'), department: t('儿科或儿童感染科', 'Pediatrics or pediatric infectious disease'), transmission: t('经唾液、飞沫和密切接触传播。', 'Through saliva, droplets and close contact.'), sourceIds: ['cdcVaccines'] }),
  D({ id: 'herpangina', name: t('疱疹性咽峡炎', 'Herpangina'), aliases: ['咽峡炎', 'Enteroviral pharyngitis'], age: age.toddler, profile: 'infectious', tags: ['infectious', 'throat', 'mouth'], location: t('口咽后部和软腭', 'Back of mouth, soft palate and pharynx'), definition: t('肠道病毒引起的发热性咽部感染，口咽后部出现小疱疹或溃疡。', 'A febrile enterovirus throat infection with small blisters or ulcers at the back of the mouth.'), cause: t('柯萨奇病毒等肠道病毒。', 'Coxsackieviruses and other enteroviruses.'), mechanism: t('病毒在口咽黏膜形成局部疱疹和溃疡，引起吞咽疼痛。', 'Virus causes local blisters and ulcers in oropharyngeal mucosa, making swallowing painful.'), symptoms: ['突然发热|咽痛和吞咽不适|软腭或咽峡小疱疹', 'Sudden fever|Sore throat and painful swallowing|Small blisters on soft palate or pharynx'], course: t('多在一周左右逐步改善，疼痛期间需重点保持液体摄入。', 'Usually improves over about a week; fluids are important while swallowing hurts.'), department: t('儿科', 'Pediatrics'), transmission: t('经粪口、呼吸道分泌物和污染表面传播。', 'Through fecal-oral spread, respiratory secretions and contaminated surfaces.'), sourceIds: ['cdcHfmd'] }),
  D({ id: 'adenovirus-infection', name: t('腺病毒感染', 'Adenovirus infection'), aliases: ['腺病毒', 'Adenovirus'], age: age.all, profile: 'infectious', tags: ['infectious', 'respiratory', 'eye', 'digestive'], location: t('呼吸道、结膜或胃肠道', 'Respiratory tract, conjunctiva or gastrointestinal tract'), definition: t('腺病毒引起的一组感染，可表现为呼吸道、眼部或胃肠道症状。', 'A group of adenovirus illnesses that may affect the respiratory tract, eyes or gut.'), cause: t('不同型别腺病毒感染。', 'Infection with different adenovirus types.'), mechanism: t('病毒感染不同部位的上皮细胞，因此表现随受累系统而变化。', 'Virus infects epithelial cells at different sites, so symptoms vary by system.'), symptoms: ['发热和咽痛或咳嗽|眼红和分泌物|可伴腹泻或呕吐', 'Fever with sore throat or cough|Red eyes and discharge|Possible diarrhea or vomiting'], course: t('多数为自限性，但高热持续、脱水或呼吸变化需要复诊。', 'Most are self-limited; persistent high fever, dehydration or breathing change needs review.'), department: t('儿科或儿童感染科', 'Pediatrics or pediatric infectious disease'), transmission: t('经呼吸道、接触、粪口和受污染水体传播。', 'Through respiratory, contact, fecal-oral routes and contaminated water.'), sourceIds: ['cdcRespiratory'] }),
  D({ id: 'acute-otitis-media', name: t('急性中耳炎', 'Acute otitis media'), aliases: ['中耳炎', 'Middle ear infection'], age: age.all, profile: 'ent', tags: ['ent', 'ear'], location: t('鼓膜后方的中耳腔', 'Middle-ear space behind the eardrum'), definition: t('中耳腔急性炎症或感染，婴幼儿常在上呼吸道感染后发生。', 'Acute inflammation or infection behind the eardrum, often after an upper respiratory illness in young children.'), cause: t('病毒或细菌在咽鼓管通气受影响后进入中耳。', 'Viruses or bacteria reach the middle ear after eustachian-tube ventilation is impaired.'), mechanism: t('中耳黏膜发炎和积液使鼓膜后压力改变，引起疼痛并可暂时影响听力。', 'Inflammation and fluid change pressure behind the eardrum, causing pain and temporary hearing effects.'), symptoms: ['耳痛、抓耳或婴儿哭闹|发热或睡眠差|听力反应下降或耳流液', 'Ear pain, pulling or infant irritability|Fever or poor sleep|Reduced hearing response or ear discharge'], course: t('不少病例数日内改善；持续疼痛、流液或听力变化需复诊。', 'Many improve over days; persistent pain, discharge or hearing change needs review.'), department: t('儿科或儿童耳鼻喉科', 'Pediatrics or pediatric ENT'), sourceIds: ['aapCommon', 'nhsChildren'] }),
  D({ id: 'otitis-externa', name: t('外耳道炎', 'Otitis externa'), aliases: ['游泳耳', 'Swimmer\'s ear'], age: age.all, profile: 'ent', tags: ['ent', 'ear'], location: t('外耳道皮肤', 'Skin of the external ear canal'), definition: t('外耳道皮肤因潮湿、损伤或感染出现炎症和疼痛。', 'Inflammation and pain of the external ear-canal skin from moisture, trauma or infection.'), cause: t('水分滞留、挖耳损伤后细菌或真菌繁殖。', 'Bacterial or fungal growth after retained water or canal trauma.'), mechanism: t('外耳道皮肤屏障破损后肿胀，使牵拉耳廓或按压耳屏疼痛。', 'Barrier injury causes canal swelling and pain when the pinna or tragus is moved.'), symptoms: ['外耳道疼痛和瘙痒|牵拉耳廓时痛|可有分泌物或堵塞感', 'Ear-canal pain and itch|Pain moving the outer ear|Possible discharge or blockage'], course: t('保持干燥并按处方局部治疗后常改善；肿胀扩展需复诊。', 'Often improves with dryness and prescribed local care; spreading swelling needs review.'), department: t('儿科或儿童耳鼻喉科', 'Pediatrics or pediatric ENT'), sourceIds: ['aapCommon'] }),
  D({ id: 'pharyngotonsillitis', name: t('咽炎或扁桃体炎', 'Pharyngitis or tonsillitis'), aliases: ['咽喉炎|扁桃体炎', 'Sore throat|Tonsillitis'], age: age.all, profile: 'ent', tags: ['ent', 'throat'], location: t('咽部黏膜与扁桃体', 'Pharyngeal mucosa and tonsils'), definition: t('咽部或扁桃体的急性炎症，可由病毒或细菌引起。', 'Acute inflammation of the throat or tonsils caused by viruses or bacteria.'), cause: t('多数为病毒；A 组链球菌等细菌也可引起，需要检测区分。', 'Most are viral; bacteria such as group A strep also occur and require testing to distinguish.'), mechanism: t('局部炎症使吞咽疼痛并可伴扁桃体肿大或渗出。', 'Local inflammation causes painful swallowing and may enlarge or coat the tonsils.'), symptoms: ['咽痛和吞咽不适|发热|颈部淋巴结或扁桃体肿大', 'Sore throat and painful swallowing|Fever|Swollen neck nodes or tonsils'], course: t('病毒性多在一周左右改善；链球菌感染需完成专业人员开具的疗程。', 'Viral illness often improves within about a week; confirmed strep needs the full prescribed course.'), department: t('儿科或儿童耳鼻喉科', 'Pediatrics or pediatric ENT'), transmission: t('感染性病因常经飞沫和密切接触传播。', 'Infectious causes commonly spread through droplets and close contact.'), sourceIds: ['aapCommon'] }),
  D({ id: 'sinusitis', name: t('鼻窦炎', 'Sinusitis'), aliases: ['儿童鼻窦炎', 'Pediatric sinusitis'], age: age.toddler, profile: 'ent', tags: ['ent', 'nose'], location: t('鼻腔与鼻窦开口', 'Nasal cavity and sinus openings'), definition: t('鼻窦黏膜炎症，儿童细菌性鼻窦炎常表现为感冒症状持续不改善或明显加重。', 'Inflammation of sinus lining; bacterial disease in children often presents as persistent or worsening cold symptoms.'), cause: t('多数先由病毒感染引起，少数因引流受阻继发细菌感染。', 'Usually begins with viral infection; some develop secondary bacterial infection after drainage is blocked.'), mechanism: t('黏膜肿胀阻碍鼻窦引流，分泌物潴留产生鼻塞、咳嗽或面部不适。', 'Swollen lining blocks drainage and retains mucus, causing congestion, cough or facial discomfort.'), symptoms: ['持续鼻涕和白天咳嗽|鼻塞或口臭|可有发热或面部不适', 'Persistent nasal discharge and daytime cough|Congestion or bad breath|Possible fever or facial discomfort'], course: t('普通病毒症状逐步改善；持续超过常见感冒病程或先好后坏需评估。', 'Ordinary viral symptoms improve gradually; persistence beyond a typical cold or worsening after improvement needs assessment.'), department: t('儿科或儿童耳鼻喉科', 'Pediatrics or pediatric ENT'), sourceIds: ['aapCommon'] }),
  D({ id: 'stomatitis', name: t('口腔溃疡或口炎', 'Mouth ulcers or stomatitis'), aliases: ['口腔溃疡|口炎', 'Oral ulcers|Stomatitis'], age: age.all, profile: 'ent', tags: ['ent', 'mouth'], location: t('口腔黏膜、舌和牙龈', 'Oral mucosa, tongue and gums'), definition: t('口腔黏膜出现单个或多个疼痛性炎症、糜烂或溃疡。', 'One or more painful inflamed, eroded or ulcerated areas of oral mucosa.'), cause: t('病毒、局部创伤、免疫反应或其他全身疾病均可能引起。', 'Viruses, local trauma, immune reactions or systemic illness may cause it.'), mechanism: t('黏膜屏障受损暴露感觉神经，导致疼痛并影响进食饮水。', 'Mucosal barrier loss exposes sensory nerves, causing pain and reduced intake.'), symptoms: ['口腔疼痛或溃疡|流涎或拒绝进食|可伴发热或牙龈红肿', 'Painful mouth ulcers|Drooling or food refusal|Possible fever or inflamed gums'], course: t('多数小溃疡在一至两周内愈合；广泛、反复或影响饮水需评估。', 'Most small ulcers heal in one to two weeks; extensive, recurrent or fluid-limiting disease needs assessment.'), department: t('儿科或儿童口腔科', 'Pediatrics or pediatric dentistry'), sourceIds: ['nhsChildren'] }),
  D({ id: 'acute-gastroenteritis', name: t('急性胃肠炎', 'Acute gastroenteritis'), aliases: ['胃肠炎|肠胃炎', 'Stomach flu|Gastroenteritis'], age: age.all, profile: 'digestive', tags: ['digestive', 'intestine', 'infectious'], location: t('胃、小肠与结肠', 'Stomach, small intestine and colon'), definition: t('急性呕吐和腹泻为主的胃肠道感染综合征，儿童主要风险是脱水。', 'An acute gastrointestinal infection with vomiting and diarrhea; dehydration is the main concern in children.'), cause: t('病毒最常见，也可由细菌或寄生虫引起。', 'Viruses are most common; bacteria and parasites can also cause it.'), mechanism: t('胃肠黏膜炎症增加水分和电解质丢失，并可能暂时影响吸收。', 'Gut inflammation increases fluid and electrolyte loss and may temporarily impair absorption.'), symptoms: ['呕吐和腹泻|腹痛或发热|尿量减少和口干提示脱水', 'Vomiting and diarrhea|Abdominal pain or fever|Less urine and dry mouth suggest dehydration'], course: t('呕吐常先缓解，腹泻可持续数日；补液和尿量趋势是观察重点。', 'Vomiting often settles first while diarrhea lasts days; hydration and urine trend are key.'), department: t('儿科或儿童消化科', 'Pediatrics or pediatric gastroenterology'), transmission: t('常经粪口途径、污染食物或密切接触传播。', 'Often through fecal-oral spread, contaminated food or close contact.'), sourceIds: ['whoChild', 'nhsChildren'] }),
  D({ id: 'viral-diarrhea', name: t('病毒性腹泻', 'Viral diarrhea'), aliases: ['轮状病毒腹泻|诺如病毒感染', 'Rotavirus diarrhea|Norovirus infection'], age: age.all, profile: 'digestive', tags: ['digestive', 'intestine', 'infectious'], location: t('小肠吸收表面', 'Small-intestinal absorptive surface'), definition: t('病毒感染肠道导致的水样腹泻，常伴呕吐或发热。', 'Watery diarrhea from viral intestinal infection, often with vomiting or fever.'), cause: t('轮状病毒、诺如病毒、腺病毒等。', 'Rotavirus, norovirus, adenovirus and others.'), mechanism: t('病毒损伤吸收细胞并促进水分进入肠腔，产生水样便。', 'Virus injures absorptive cells and shifts water into the bowel, producing watery stools.'), symptoms: ['水样腹泻|呕吐或发热|脱水迹象', 'Watery diarrhea|Vomiting or fever|Signs of dehydration'], course: t('多在数日内改善；婴儿因储备少更需密切观察补液和尿量。', 'Usually improves over days; infants need closer fluid and urine observation because reserves are smaller.'), department: t('儿科或儿童消化科', 'Pediatrics or pediatric gastroenterology'), transmission: t('粪口途径和污染表面传播。', 'Fecal-oral spread and contaminated surfaces.'), sourceIds: ['whoChild'] }),
  D({ id: 'functional-constipation', name: t('功能性便秘', 'Functional constipation'), aliases: ['儿童便秘', 'Childhood constipation'], age: age.toddler, profile: 'digestive', tags: ['digestive', 'intestine'], location: t('结肠、直肠与排便协调', 'Colon, rectum and defecation coordination'), definition: t('没有明确器质性病因的排便困难、粪便干硬或排便间隔延长。', 'Difficult, hard or infrequent stools without an identified structural disease.'), cause: t('疼痛后憋便、饮食变化、如厕训练和生活节律常共同作用。', 'Withholding after painful stools, diet change, toilet training and routine often interact.'), mechanism: t('粪便在结肠停留越久水分被吸收越多，排便疼痛又强化憋便循环。', 'Longer colonic transit removes more water, and painful stools reinforce withholding.'), symptoms: ['干硬或粗大粪便|排便疼痛和憋便动作|腹胀或少量漏便', 'Hard or large stools|Pain and withholding behavior|Bloating or small stool leaks'], course: t('常需数周至数月建立无痛规律排便，按计划随访比短期通便更重要。', 'Restoring painless regular stools may take weeks to months; planned follow-up matters more than a brief purge.'), department: t('儿科或儿童消化科', 'Pediatrics or pediatric gastroenterology'), sourceIds: ['nhsChildren'] }),
  D({ id: 'lactose-intolerance', name: t('乳糖不耐受', 'Lactose intolerance'), aliases: ['乳糖酶缺乏', 'Lactase deficiency'], age: age.all, profile: 'digestive', tags: ['digestive', 'intestine'], location: t('小肠刷状缘乳糖酶与结肠发酵', 'Small-intestinal lactase and colonic fermentation'), definition: t('乳糖消化不足后出现腹胀、腹痛或腹泻，不等同于牛奶蛋白过敏。', 'Symptoms from incomplete lactose digestion; it is not the same as cow\'s-milk protein allergy.'), cause: t('原发性乳糖酶下降或胃肠炎后暂时性乳糖酶不足。', 'Primary lactase decline or temporary deficiency after gastroenteritis.'), mechanism: t('未消化乳糖进入结肠后吸水并被细菌发酵，产生气体和稀便。', 'Undigested lactose draws water into the bowel and is fermented, producing gas and loose stools.'), symptoms: ['摄入乳糖后腹胀或腹痛|排气增多|稀便', 'Bloating or pain after lactose|More gas|Loose stools'], course: t('继发性常随肠黏膜恢复而改善；长期限制前应确认原因并保证营养。', 'Secondary intolerance often improves as mucosa heals; confirm cause and nutrition before long-term restriction.'), department: t('儿科或儿童消化科', 'Pediatrics or pediatric gastroenterology'), sourceIds: ['nhsChildren'] }),
  D({ id: 'intussusception', name: t('肠套叠', 'Intussusception'), aliases: ['小儿肠套叠', 'Telescoping bowel'], age: age.toddler, profile: 'digestive', tags: ['digestive', 'intestine'], location: t('回肠末端与结肠等肠段', 'Bowel segments, often terminal ileum and colon'), definition: t('一段肠管套入相邻肠段造成梗阻和血供受压，是需要急诊评估的结构性问题。', 'One bowel segment telescopes into another, causing obstruction and pressure on blood supply; it needs emergency assessment.'), cause: t('多数婴幼儿无明确诱因，部分与淋巴组织增生或结构性病变有关。', 'Many young-child cases have no clear trigger; some involve enlarged lymph tissue or a structural lead point.'), mechanism: t('套入肠段阻碍内容物通过并压迫血管，持续时可损伤肠壁。', 'Telescoping blocks passage and compresses vessels, potentially injuring bowel if prolonged.'), symptoms: ['阵发性剧烈腹痛和蜷腿|呕吐或精神萎靡|血黏液便并非总会出现', 'Episodes of severe pain with leg drawing|Vomiting or lethargy|Bloody mucus stool is not always present'], course: t('症状可间歇出现但不能等待自行消失，需要影像和及时复位或手术评估。', 'Symptoms may come and go but should not be watched for spontaneous resolution; imaging and prompt reduction or surgery assessment are needed.'), department: t('儿童急诊或儿童外科', 'Pediatric emergency or pediatric surgery'), sourceIds: ['nhsChildren'] }),
  D({ id: 'appendicitis', name: t('急性阑尾炎', 'Acute appendicitis'), aliases: ['阑尾炎', 'Appendicitis'], age: age.all, profile: 'digestive', tags: ['digestive', 'intestine'], location: t('盲肠旁阑尾', 'Appendix beside the cecum'), definition: t('阑尾急性炎症，幼儿表现可能不典型但需要及时外科评估。', 'Acute inflammation of the appendix; signs may be atypical in young children but timely surgical assessment is needed.'), cause: t('阑尾腔阻塞后细菌增殖和炎症最常见。', 'Obstruction of the appendix followed by bacterial growth and inflammation is typical.'), mechanism: t('腔内压力和炎症增加可影响阑尾血供并导致穿孔。', 'Rising pressure and inflammation can impair blood supply and lead to perforation.'), symptoms: ['持续或逐渐加重腹痛|呕吐、食欲下降或发热|走动、咳嗽时腹痛加重', 'Persistent or worsening abdominal pain|Vomiting, poor appetite or fever|Pain worse with movement or cough'], course: t('通常不会靠家庭护理消退；怀疑时需急诊查体、化验和影像。', 'It does not usually resolve with home care; suspected cases need urgent examination, tests and imaging.'), department: t('儿童急诊或儿童外科', 'Pediatric emergency or pediatric surgery'), sourceIds: ['nhsChildren'] }),
  D({ id: 'urticaria', name: t('荨麻疹', 'Urticaria'), aliases: ['风团|风疹块', 'Hives|Wheals'], age: age.all, profile: 'skin', tags: ['skin', 'allergy'], location: t('真皮浅层血管与全身皮肤表面', 'Superficial dermal vessels and skin surfaces'), definition: t('短暂隆起、瘙痒且位置会变化的风团，可由感染、食物、药物或其他因素触发。', 'Transient itchy raised wheals that move or change, triggered by infection, foods, medicines or other factors.'), cause: t('肥大细胞释放组胺；儿童急性病例常与病毒感染有关，也可能为过敏反应。', 'Histamine release from mast cells; acute cases in children often follow viruses but may be allergic.'), mechanism: t('皮肤浅层血管通透性增加，液体短暂进入真皮形成风团。', 'Increased permeability of superficial skin vessels briefly forms wheals.'), symptoms: ['瘙痒性隆起风团|单个皮疹常在数小时内移动或消退|可伴眼唇肿胀', 'Itchy raised wheals|Individual lesions move or fade within hours|Possible eyelid or lip swelling'], course: t('多数急性病例在数日内消退；伴呼吸、声音或循环变化属于紧急情况。', 'Most acute cases settle over days; breathing, voice or circulation changes are an emergency.'), department: t('儿科、儿童皮肤科或过敏专科', 'Pediatrics, pediatric dermatology or allergy medicine'), sourceIds: ['nhsSkin'], escalationRuleRef: 'decision-unit:general_health_preassessment' }),
  D({ id: 'food-allergy', name: t('食物过敏', 'Food allergy'), aliases: ['食物过敏反应', 'Food-allergic reaction'], age: age.all, profile: 'skin', tags: ['skin', 'allergy', 'digestive'], location: t('免疫系统，可影响皮肤、胃肠道和呼吸道', 'Immune system, potentially affecting skin, gut and airways'), definition: t('免疫系统对特定食物蛋白产生反应，可累及一个或多个器官系统。', 'An immune response to a specific food protein that may affect one or several organ systems.'), cause: t('对牛奶、蛋、花生、坚果、小麦、大豆、鱼或甲壳类等食物蛋白致敏。', 'Sensitization to proteins such as milk, egg, peanut, tree nuts, wheat, soy, fish or shellfish.'), mechanism: t('再次暴露触发免疫介质释放，快速型反应可在短时间内累及多个系统。', 'Re-exposure releases immune mediators; immediate reactions can involve multiple systems quickly.'), symptoms: ['进食后风团或肿胀|呕吐、腹痛或腹泻|咳嗽、喘鸣、声音或精神变化', 'Hives or swelling after food|Vomiting, pain or diarrhea|Cough, wheeze, voice or alertness change'], course: t('反应速度和严重度可变；明确诊断与回避计划应由过敏专科制定。', 'Timing and severity vary; diagnosis and avoidance plans should be set by allergy specialists.'), department: t('儿科或儿童过敏专科', 'Pediatrics or pediatric allergy medicine'), sourceIds: ['nhsChildren'] }),
  D({ id: 'contact-dermatitis', name: t('接触性皮炎', 'Contact dermatitis'), aliases: ['刺激性皮炎|过敏性接触皮炎', 'Irritant dermatitis|Allergic contact dermatitis'], age: age.all, profile: 'skin', tags: ['skin'], location: t('与物品接触的皮肤表面', 'Skin surfaces exposed to a product or material'), definition: t('皮肤接触刺激物或过敏原后出现局限性红、痒、干燥或水疱。', 'Localized red, itchy, dry or blistered skin after contact with an irritant or allergen.'), cause: t('清洁剂、口水、金属、胶黏剂、香精或植物等直接刺激或致敏。', 'Direct irritation or allergy from cleansers, saliva, metals, adhesives, fragrance or plants.'), mechanism: t('化学刺激直接损伤屏障，或迟发型免疫反应造成局部炎症。', 'Chemical irritation damages the barrier, or a delayed immune response causes local inflammation.'), symptoms: ['接触区域边界相对清楚的红疹|瘙痒、刺痛或干裂|可有小水疱或渗液', 'A fairly defined rash at contact sites|Itch, stinging or cracks|Possible small blisters or weeping'], course: t('去除诱因后逐渐改善；反复时需通过接触史或斑贴试验寻找原因。', 'Improves after trigger removal; recurrent disease may need exposure review or patch testing.'), department: t('儿科或儿童皮肤科', 'Pediatrics or pediatric dermatology'), sourceIds: ['nhsSkin'] }),
  D({ id: 'heat-rash', name: t('痱子', 'Heat rash'), aliases: ['汗疹|粟粒疹', 'Prickly heat|Miliaria'], age: age.all, profile: 'skin', tags: ['skin'], location: t('汗管开口和易闷热皮肤褶皱', 'Sweat ducts and warm occluded skin folds'), definition: t('汗管暂时堵塞后出现密集小红点或小疱，婴儿在闷热环境更常见。', 'Clusters of small red spots or blisters from temporarily blocked sweat ducts, common in warm infants.'), cause: t('炎热、潮湿、包裹过多或不透气衣物使汗液潴留。', 'Heat, humidity, over-bundling or non-breathable clothing retain sweat.'), mechanism: t('汗液不能顺利排出并渗入表浅皮肤，引起刺激性炎症。', 'Trapped sweat leaks into superficial skin and causes irritation.'), symptoms: ['颈部、胸背或褶皱密集小疹|刺痒或烦躁|通常无明显全身不适', 'Clusters on neck, trunk or folds|Prickling itch or irritability|Usually no systemic illness'], course: t('降温、通风和减少包裹后常在数日内消退。', 'Often clears within days after cooling, ventilation and less bundling.'), department: t('儿科或儿童皮肤科', 'Pediatrics or pediatric dermatology'), sourceIds: ['nhsSkin'] }),
  D({ id: 'impetigo', name: t('脓疱疮', 'Impetigo'), aliases: ['传染性脓疱病', 'School sores'], age: age.all, profile: 'skin', tags: ['skin', 'infectious'], location: t('表皮，常见于鼻口周围和破损皮肤', 'Epidermis, often around nose and mouth or broken skin'), definition: t('金黄色葡萄球菌或链球菌引起的浅表传染性皮肤感染。', 'A contagious superficial skin infection caused by staphylococci or streptococci.'), cause: t('细菌经抓痕、湿疹或虫咬等屏障破口进入表皮。', 'Bacteria enter epidermis through scratches, eczema or bites.'), mechanism: t('表浅感染形成水疱、脓疱并破裂结成蜂蜜色痂。', 'Superficial infection forms blisters or pustules that rupture into honey-colored crusts.'), symptoms: ['蜂蜜色痂皮|小水疱或脓疱|周围可瘙痒并逐渐扩散', 'Honey-colored crusts|Small blisters or pustules|Itch and gradual spread'], course: t('需要规范局部或口服处方治疗；治疗前后注意减少传播。', 'Needs prescribed topical or oral treatment; reduce spread before and during treatment.'), department: t('儿科或儿童皮肤科', 'Pediatrics or pediatric dermatology'), transmission: t('通过皮损直接接触或共用毛巾、衣物传播。', 'Through direct lesion contact or shared towels and clothing.'), sourceIds: ['aapCommon'] }),
  D({ id: 'fungal-skin-infection', name: t('常见真菌性皮肤感染', 'Common fungal skin infection'), aliases: ['体癣|股癣|足癣', 'Ringworm|Tinea'], age: age.all, profile: 'skin', tags: ['skin', 'infectious'], location: t('皮肤角质层、头皮或趾间', 'Outer skin layer, scalp or toe webs'), definition: t('皮肤癣菌感染角质层或毛发形成环形、脱屑或局部脱发等表现。', 'Dermatophyte infection of outer skin or hair, causing rings, scale or localized hair loss.'), cause: t('皮肤癣菌通过人与人、动物或污染物品接触传播。', 'Dermatophytes spread from people, animals or contaminated objects.'), mechanism: t('真菌利用角蛋白在表层向外生长，边缘炎症常比中央明显。', 'Fungi use keratin and grow outward in superficial layers, often with a more inflamed edge.'), symptoms: ['环形脱屑红斑|瘙痒|头皮感染可有断发或脱发斑', 'Ring-shaped scaly redness|Itch|Scalp infection may break hair or cause bald patches'], course: t('需按部位完成足够疗程；头皮或广泛感染通常需要专业评估。', 'Requires a sufficient site-specific course; scalp or widespread disease usually needs clinical review.'), department: t('儿科或儿童皮肤科', 'Pediatrics or pediatric dermatology'), transmission: t('直接接触感染者、动物或污染物品。', 'Direct contact with infected people, animals or objects.'), sourceIds: ['aapCommon'] }),
  D({ id: 'conjunctivitis', name: t('结膜炎', 'Conjunctivitis'), aliases: ['红眼病|结膜感染', 'Pink eye'], age: age.all, profile: 'eye', tags: ['eye', 'eyeball', 'infectious'], location: t('眼睑内面与眼白表面的结膜', 'Conjunctiva lining eyelids and covering the white of the eye'), definition: t('结膜因病毒、细菌、过敏或刺激出现红、痒和分泌物。', 'Red, itchy or discharging conjunctiva from viral, bacterial, allergic or irritant causes.'), cause: t('呼吸道病毒、细菌、过敏原或化学刺激。', 'Respiratory viruses, bacteria, allergens or chemical irritation.'), mechanism: t('结膜血管扩张和炎症产生红眼、流泪或分泌物。', 'Dilated conjunctival vessels and inflammation cause redness, tearing or discharge.'), symptoms: ['眼红和流泪|黏性或脓性分泌物|瘙痒或异物感', 'Red watery eyes|Sticky or purulent discharge|Itch or gritty feeling'], course: t('病因不同病程不同；疼痛、畏光、视力变化或眼周明显肿胀需及时评估。', 'Course varies by cause; pain, light sensitivity, vision change or marked surrounding swelling needs prompt review.'), department: t('儿科或儿童眼科', 'Pediatrics or pediatric ophthalmology'), transmission: t('病毒和细菌性类型可经手、分泌物和共用物品传播。', 'Viral and bacterial forms can spread via hands, discharge and shared items.'), sourceIds: ['nhsChildren'] }),
  D({ id: 'stye', name: t('麦粒肿', 'Stye'), aliases: ['针眼|睑腺炎', 'Hordeolum'], age: age.all, profile: 'eye', tags: ['eye', 'eyeball'], location: t('眼睑睫毛根部或睑板腺', 'Eyelash follicle or meibomian gland'), definition: t('眼睑腺体或睫毛毛囊的急性局部感染，形成疼痛小肿块。', 'A localized acute infection of an eyelid gland or lash follicle causing a painful lump.'), cause: t('常由葡萄球菌在堵塞或受刺激的腺体中繁殖。', 'Often staphylococcal growth in a blocked or irritated gland.'), mechanism: t('局部腺体堵塞并发炎，形成红肿和脓点。', 'A blocked gland inflames, forming redness, swelling and sometimes a pustule.'), symptoms: ['眼睑边缘疼痛肿块|局部红肿|可有流泪', 'Painful eyelid-edge lump|Localized redness and swelling|Possible tearing'], course: t('多数经温热敷和清洁逐步消退；不消退、扩散或影响睁眼需评估。', 'Most settle with warm compresses and hygiene; persistence, spread or impaired opening needs review.'), department: t('儿科或儿童眼科', 'Pediatrics or pediatric ophthalmology'), sourceIds: ['nhsChildren'] }),
  D({ id: 'urinary-tract-infection', name: t('儿童尿路感染', 'Childhood urinary tract infection'), aliases: ['UTI|膀胱炎', 'UTI|Bladder infection'], age: age.all, profile: 'urinary', tags: ['urinary', 'kidneys'], location: t('尿道、膀胱，部分累及输尿管或肾脏', 'Urethra and bladder, sometimes ureters or kidneys'), definition: t('细菌在尿路繁殖引起的感染，婴儿可能只有发热、吃奶差或精神变化。', 'Bacterial infection in the urinary tract; infants may present only with fever, poor feeding or alertness change.'), cause: t('肠道细菌经尿道上行最常见。', 'Ascending bacteria from the bowel are most common.'), mechanism: t('细菌在膀胱黏膜引起炎症，上行时可影响肾盂和肾组织。', 'Bacteria inflame bladder lining and may ascend to the renal pelvis and kidney.'), symptoms: ['排尿痛、尿频或尿急|发热或腹腰痛|婴儿可吃奶差、呕吐或精神改变', 'Pain, frequency or urgency with urine|Fever or abdominal/back pain|Infants may feed poorly, vomit or be less alert'], course: t('需要规范尿样确认并按培养和年龄完成治疗；反复发热性 UTI 可能需结构评估。', 'Needs a proper urine sample and age-appropriate treatment guided by testing; recurrent febrile UTI may need structural assessment.'), department: t('儿科、儿童肾脏科或泌尿科', 'Pediatrics, pediatric nephrology or urology'), sourceIds: ['aapCommon'] }),
  D({ id: 'balanitis', name: t('包皮龟头炎', 'Balanitis'), aliases: ['龟头炎', 'Inflamed glans'], age: age.all, profile: 'urinary', tags: ['urinary'], location: t('阴茎头与包皮表面', 'Glans and foreskin surface'), definition: t('龟头或包皮的局部炎症，可由刺激、卫生问题或感染引起。', 'Local inflammation of the glans or foreskin from irritation, hygiene issues or infection.'), cause: t('尿液、肥皂、摩擦、细菌或真菌均可能造成。', 'Urine, soap, friction, bacteria or yeast may contribute.'), mechanism: t('局部屏障受刺激后红肿疼痛，分泌物积聚可加重炎症。', 'Barrier irritation causes redness and pain; retained discharge can worsen inflammation.'), symptoms: ['龟头或包皮红肿疼痛|排尿不适|可有分泌物或异味', 'Red painful glans or foreskin|Discomfort urinating|Possible discharge or odor'], course: t('温和清洁和针对病因处理后多改善；排尿困难或肿胀明显需及时评估。', 'Often improves with gentle hygiene and cause-specific care; difficulty urinating or marked swelling needs prompt review.'), department: t('儿科或儿童泌尿外科', 'Pediatrics or pediatric urology'), sourceIds: ['nhsChildren'] }),
  D({ id: 'vulvovaginitis', name: t('女童外阴阴道炎', 'Prepubertal vulvovaginitis'), aliases: ['外阴炎', 'Vulvitis'], age: age.toddler, profile: 'urinary', tags: ['urinary'], location: t('外阴与阴道口周围皮肤黏膜', 'Vulva and tissue around the vaginal opening'), definition: t('青春期前女童常见的外阴和阴道口刺激或炎症。', 'Common irritation or inflammation of the vulva and vaginal opening before puberty.'), cause: t('潮湿、肥皂刺激、清洁方向、紧身衣物或感染等。', 'Moisture, soap, wiping direction, tight clothing or infection.'), mechanism: t('较薄的黏膜受刺激后出现红、痒、疼痛和分泌物。', 'Thin mucosa becomes irritated, causing redness, itch, pain and discharge.'), symptoms: ['外阴红痒或疼痛|排尿时刺痛|可有少量分泌物', 'Vulvar redness, itch or pain|Stinging with urine|Possible small discharge'], course: t('改善温和卫生和通风后常缓解；持续、血性或异味分泌物需评估。', 'Often improves with gentle hygiene and ventilation; persistent, bloody or foul discharge needs review.'), department: t('儿科或儿童妇科', 'Pediatrics or pediatric gynecology'), sourceIds: ['nhsChildren'] }),
  D({ id: 'febrile-seizure', name: t('热性惊厥', 'Febrile seizure'), aliases: ['高热惊厥|发热抽搐', 'Fever seizure'], age: [180, 1825, t('约 6 个月至 5 岁', 'About 6 months to 5 years')], profile: 'neurologic', tags: ['neurologic', 'brain'], location: t('发育中的神经系统对发热的短暂反应', 'A transient response of the developing nervous system to fever'), definition: t('特定年龄儿童发热期间发生的惊厥，需要首次评估并排除中枢感染等原因。', 'A seizure during fever in an age-defined child; a first event needs assessment to exclude other causes such as CNS infection.'), cause: t('感染引起发热，在易感年龄触发惊厥；通常不是癫痫。', 'Fever from infection triggers a seizure at a susceptible age; it is usually not epilepsy.'), mechanism: t('发育中脑网络在发热背景下短暂出现同步异常放电。', 'Developing brain networks briefly produce synchronized abnormal activity during fever.'), symptoms: ['意识丧失和全身僵硬或抽动|通常持续短暂|发作后嗜睡并逐渐恢复', 'Loss of awareness with generalized stiffening or jerking|Usually brief|Sleepiness followed by recovery'], course: t('多数单纯型预后良好，但首次、持续时间长、局灶或恢复异常需急诊评估。', 'Most simple events have a good outlook, but first, prolonged, focal or poorly recovering events need emergency assessment.'), department: t('儿童急诊、儿科或儿童神经科', 'Pediatric emergency, pediatrics or pediatric neurology'), sourceIds: ['nhsChildren'] }),
  D({ id: 'iron-deficiency-anemia', name: t('缺铁性贫血', 'Iron-deficiency anemia'), aliases: ['缺铁贫血', 'Iron deficiency'], age: age.all, profile: 'nutrition', tags: ['nutrition', 'blood'], location: t('血红蛋白合成与全身氧运输', 'Hemoglobin production and oxygen transport'), definition: t('体内铁不足影响血红蛋白合成形成的贫血。', 'Anemia caused by insufficient iron for hemoglobin production.'), cause: t('铁摄入不足、需求增加、吸收问题或慢性失血。', 'Low intake, increased requirement, absorption problems or chronic blood loss.'), mechanism: t('血红蛋白减少使红细胞携氧能力下降，长期缺铁也可影响发育。', 'Less hemoglobin reduces oxygen-carrying capacity; prolonged deficiency may also affect development.'), symptoms: ['面色苍白|易疲劳或活动耐力下降|食欲、注意或生长变化', 'Pallor|Fatigue or lower stamina|Changes in appetite, attention or growth'], course: t('需通过血常规和铁代谢确认原因，按计划补铁和复查直至储备恢复。', 'Blood count and iron studies confirm cause; planned iron treatment and follow-up continue until stores recover.'), department: t('儿科、儿童保健科或血液科', 'Pediatrics, child health or pediatric hematology'), sourceIds: ['whoChild'] }),
  D({ id: 'vitamin-d-deficiency-rickets', name: t('维生素 D 缺乏或佝偻病', 'Vitamin D deficiency or rickets'), aliases: ['佝偻病|维D缺乏', 'Rickets|Vitamin D deficiency'], age: age.all, profile: 'nutrition', tags: ['nutrition', 'bone'], location: t('骨骼生长板与钙磷矿化', 'Growth plates and calcium-phosphate mineralization'), definition: t('维生素 D、钙或磷不足导致骨矿化受影响；出现骨骼改变时称佝偻病。', 'Impaired bone mineralization from vitamin D, calcium or phosphate problems; skeletal changes are called rickets.'), cause: t('摄入或日照不足、吸收不良，或肝肾和遗传性代谢问题。', 'Low intake or sunlight, malabsorption, or liver, kidney and inherited metabolic problems.'), mechanism: t('钙磷供应或调节不足使快速生长的骨骼和生长板不能正常矿化。', 'Inadequate calcium-phosphate supply or regulation prevents normal mineralization of growing bone and growth plates.'), symptoms: ['早期可能无明显症状|骨骼变形或肌力下降|生长和出牙变化需综合评估', 'Early disease may have no obvious symptoms|Bone deformity or reduced muscle strength|Growth and tooth changes need full assessment'], course: t('按原因补充并复查后可改善；不能仅凭外观判断或自行使用大剂量。', 'Improves with cause-specific supplementation and follow-up; appearance alone is not diagnostic and high doses should not be self-used.'), department: t('儿科、儿童保健科或儿童内分泌科', 'Pediatrics, child health or pediatric endocrinology'), sourceIds: ['whoChild'] }),
]

const PLANNED_ORGANS = [
  { id: 'ear', name: t('耳与中耳', 'Ear & middle ear'), system: t('耳鼻喉系统', 'ENT system') },
  { id: 'nose', name: t('鼻腔与鼻窦', 'Nose & sinuses'), system: t('呼吸系统', 'Respiratory system') },
  { id: 'throat', name: t('咽喉', 'Throat & larynx'), system: t('呼吸与吞咽', 'Breathing & swallowing') },
  { id: 'mouth', name: t('口腔', 'Mouth'), system: t('口腔与消化入口', 'Oral & digestive entry') },
  { id: 'stomach', name: t('胃与食管', 'Stomach & esophagus'), system: t('消化系统', 'Digestive system') },
  { id: 'bladder', name: t('膀胱与下尿路', 'Bladder & lower urinary tract'), system: t('泌尿系统', 'Urinary system') },
  { id: 'bone', name: t('骨骼', 'Bones'), system: t('骨骼系统', 'Skeletal system') },
]

const ORGAN_COPY = Object.freeze({
  heart: { function: t('通过有节律的收缩把血液泵向全身，输送氧和营养。', 'Rhythmic contractions pump blood through the body, carrying oxygen and nutrients.'), child: t('婴儿心率通常较快，心脏结构和循环仍在发育。', 'Infant heart rates are often faster while cardiac structure and circulation continue to develop.') },
  brain: { function: t('整合感觉、运动、学习和情绪反应，参与身体控制。', 'The brain integrates sensation, movement, learning, emotion, and body control.'), child: t('婴幼儿神经连接持续建立，反应速度和互动方式差异很大。', 'Neural connections keep forming in early childhood, so responses and interaction vary widely.') },
  lungs: { function: t('通过气道通气和肺泡气体交换，为身体补充氧气。', 'The airways and alveoli move air and exchange gases to supply oxygen.'), child: t('婴幼儿气道较细，呼吸频率和呼吸模式会随年龄变化。', 'Young children have narrower airways, and breathing rate and pattern change with age.') },
  liver: { function: t('处理营养和代谢产物，合成蛋白并生成胆汁。', 'The liver processes nutrients and metabolites, makes proteins, and produces bile.'), child: t('儿童肝脏代谢能力仍在成熟，不能直接套用成人用量。', 'Liver metabolism is still maturing in children; adult doses should not be copied.') },
  kidneys: { function: t('过滤血液、调节水盐平衡，并形成尿液。', 'The kidneys filter blood, regulate fluid and salts, and make urine.'), child: t('儿童肾脏和尿路仍在发育，尿量和排尿模式会随年龄变化。', 'The kidneys and urinary tract are still developing, so urine output and patterns vary by age.') },
  eyeball: { function: t('聚焦进入眼内的光线，并把视觉信息传给大脑。', 'The eye focuses incoming light and sends visual information to the brain.'), child: t('视觉功能需要在出生后逐步发展，双眼协调会随年龄变化。', 'Vision develops after birth, and coordination between the eyes changes with age.') },
  intestine: { function: t('完成食物消化吸收，并回收水分、维护肠道屏障。', 'The intestine digests and absorbs food, reclaims water, and supports the gut barrier.'), child: t('婴幼儿消化和排便模式变化较快，观察趋势比单次表现更有用。', 'Digestion and stool patterns change quickly in infancy; trends are more useful than one event.') },
  pancreas: { function: t('分泌消化酶，并参与血糖调节。', 'The pancreas releases digestive enzymes and helps regulate blood sugar.'), child: t('儿童胰腺功能与饮食需求随生长变化，信息仅作结构学习。', 'Pancreatic function and dietary needs change with growth; this is for anatomy learning only.') },
  skin: { function: t('形成保护屏障，参与感觉、体温调节和水分保持。', 'The skin forms a protective barrier and supports sensation, temperature, and water balance.'), child: t('婴幼儿皮肤屏障较薄，容易受潮湿、摩擦和温度影响。', 'Infant skin barriers are thinner and more affected by moisture, friction, and temperature.') },
  ear: { function: t('接收声音并参与平衡，外耳、中耳和内耳共同工作。', 'The outer, middle, and inner ear receive sound and support balance.'), child: t('儿童耳道和听觉通路仍在发育，感冒后耳部变化值得记录。', 'The ear canal and hearing pathways are still developing; note changes after colds.') },
  nose: { function: t('过滤、加温和湿润吸入空气，也参与嗅觉。', 'The nose filters, warms, and humidifies air and supports smell.'), child: t('婴幼儿鼻腔较窄，鼻塞对吃奶和睡眠的影响更明显。', 'Infants have narrow nasal passages, so congestion can affect feeding and sleep more.') },
  throat: { function: t('连接呼吸和吞咽通路，参与发声并保护气道。', 'The throat connects breathing and swallowing pathways, supports voice, and protects the airway.'), child: t('婴幼儿吞咽与呼吸协调仍在成熟，喂养时要观察是否呛咳。', 'Breathing and swallowing coordination is still maturing; watch for coughing during feeds.') },
  mouth: { function: t('承担吸吮、咀嚼、吞咽和口腔屏障功能。', 'The mouth supports sucking, chewing, swallowing, and an oral barrier.'), child: t('口腔黏膜和牙齿处于发育阶段，喂养与清洁方式需按年龄调整。', 'Oral tissues and teeth are developing, so feeding and cleaning should fit the age.') },
  stomach: { function: t('暂存并搅拌食物，开始消化并将内容物送入肠道。', 'The stomach stores and mixes food, starts digestion, and passes contents to the intestine.'), child: t('婴儿胃容量小、食管括约肌仍在成熟，喂后表现要结合进食量观察。', 'Infant stomachs are small and the esophageal valve is maturing; interpret post-feed signs with intake.') },
  bladder: { function: t('储存尿液，并与尿道协同完成排尿。', 'The bladder stores urine and works with the urethra for emptying.'), child: t('幼儿排尿控制逐步建立，次数、颜色和疼痛等变化要结合年龄看。', 'Toilet control develops gradually; interpret frequency, color, and pain by age.') },
  bone: { function: t('支撑身体并保护器官，骨骼和生长板也是运动基础。', 'Bones support the body, protect organs, and provide the basis for movement and growth.'), child: t('儿童骨骼和生长板仍在发育，外观不能替代专业评估。', 'Children’s bones and growth plates are developing; appearance cannot replace assessment.') },
})

export const ORGAN_TOPICS = Object.freeze([
  ...ANATOMY_RESOURCES.map((resource) => ({
    ...ORGAN_COPY[resource.id],
    id: resource.id,
    name: resource.title,
    system: resource.system,
    shortFunction: t('通过儿童解剖模型认识结构、位置和基础功能。', 'Use a pediatric anatomy model to learn structure, location and basic function.'),
    childSpecificNotes: [ORGAN_COPY[resource.id]?.child || t('儿童结构和生理仍在发育。', 'Children\'s structure and physiology are still developing.'), t('模型用于教学，不用于诊断。', 'The model teaches anatomy and does not diagnose.')],
    anatomyAnchors: [],
    modelAvailability: resource.model ? 'AVAILABLE' : 'PLANNED',
    modelRef: resource.model || null,
    relatedDiseaseIds: DISEASE_TOPICS.filter((topic) => topic.categoryTags.includes(resource.id)).map((topic) => topic.id),
  })),
  ...PLANNED_ORGANS.map((organ) => ({
    ...organ,
    ...ORGAN_COPY[organ.id],
    shortFunction: t('认识该结构的基本功能，以及儿童阶段常见疾病发生在哪里。', 'Learn the structure\'s basic function and where common childhood illnesses occur.'),
    childSpecificNotes: [ORGAN_COPY[organ.id]?.child || t('儿童结构和生理仍在发育。', 'Children\'s structure and physiology are still developing.'), t('没有模型时文字指导仍完整可用。', 'Text guidance remains available without a model.')],
    anatomyAnchors: [],
    modelAvailability: 'PLANNED',
    modelRef: null,
    relatedDiseaseIds: DISEASE_TOPICS.filter((topic) => topic.categoryTags.includes(organ.id)).map((topic) => topic.id),
  })),
])

export function getDiseaseTopic(id) {
  return DISEASE_TOPICS.find((topic) => topic.id === id) || DISEASE_TOPICS[0]
}

export function searchDiseaseTopics(query = '', locale = 'zh-CN') {
  const needle = String(query).trim().toLocaleLowerCase()
  if (!needle) return DISEASE_TOPICS
  const language = locale === 'en-US' ? 'en' : 'zh'
  return DISEASE_TOPICS.filter((topic) => [topic.name, topic.category, topic.shortDefinition, ...topic.aliases]
    .some((value) => String(value?.[language] || value?.zh || '').toLocaleLowerCase().includes(needle)))
}

export function diseasesForOrgan(organId) {
  return DISEASE_TOPICS.filter((topic) => topic.anatomyBinding.displayUnits.some((unit) => unit.modelRef?.includes(organId)) || topic.categoryTags.includes(organId))
}
